/**
 * AI Racing Commentary Vocabulary Matrix
 * Kho từ vựng & dữ liệu bình luận tổ hợp siêu khổng lồ (Hơn 150 TỶ TỶ BIẾN THỂ KẾT HỢP)
 * Phong cách F1, Thể Thao Đỉnh Cao, TikTok Meme, Trẻ Trâu Hài Hước Bùng Nổ
 */

import { CommentaryCategory } from './commentaryGenerator';

export interface DriverCommentaryProfile {
  name: string;
  aliases: string[];
  signatureGag: string;
  shoutout: string;
}

// 1. MA TRẬN MỞ MÀN / CẢM XÚC HYPE (100 HOOKS)
export const MASSIVE_HOOKS: string[] = [
  "Úi giời ơi anh em ơi!",
  "Kính thưa toàn thể 500 anh em đang nín thở theo dõi!",
  "Chấn động địa cầu, rúng động cả trường đua!",
  "Đèn xanh vừa bật sáng lóa cả màn hình!",
  "Trời đất ơi, một pha xử lý không thể tin vào mắt mình!",
  "Xem kìa anh em ơi, chuyện gì đang xảy ra thế này?!",
  "Cả trường đua đang rung chuyển từng mét đường nhựa bốc khói!",
  "Mùi cao su cháy khét lẹt xộc thẳng vào buồng bình luận rồi!",
  "Tốc độ này thì đồng hồ công-tơ-mét cũng phải vỡ kính hiển thị!",
  "Ối dồi ôi, hôm nay uống nhầm lon tăng lực hay sao mà chạy khiếp thế?!",
  "Không thể đỉnh hơn được nữa quý vị ơi!",
  "Bình luận viên rụng rời tay chân, tim đập thình thịch 200 nhịp!",
  "Lạy chúa tôi, một khoảnh khắc xứng đáng đi thẳng vào sách giáo khoa!",
  "Toàn bộ khán đài đồng loạt đứng bật dậy gào thét khản cổ!",
  "Pha xử lý đẳng cấp vũ trụ vừa được tái hiện trên đường đua!",
  "Bá cháy bọ chét luôn anh em ơi!",
  "Tổ lái nhập rồi, chính thức bật chế độ siêu nhân!",
  "Hú hồn chim én, một pha ra xe khiến tim người xem muốn rớt ra ngoài!",
  "Ối giời ơi cứu tôi với, tốc độ này là người ngoài hành tinh lái xe chứ người thường sao lái nổi?!",
  "Đỉnh nóc kịch trần, bay phấp phới không một tì vết!",
  "Một pha bẻ lái đi vào lòng đất đối thủ và đi vào lòng người hâm mộ!",
  "Khét lẹt luôn anh em ơi, khét hơn cả nồi cơm cháy của mẹ!",
  "Chuông báo động khẩn cấp rú ầm ĩ khắp các góc cua!",
  "Cảnh tượng điên rồ nhất mà tôi từng chứng kiến trong 20 năm làm nghề bình luận!",
  "Quá kinh khủng khiếp, một con quái thú bọc thép thực sự xổng chuồng!",
  "Nín thở nào quý vị ơi, một phần trăm giây quyết định số phận!",
  "Cháy máy luôn rồi, kim nhiệt độ đang chỉ thẳng lên vạch đỏ!",
  "Bão táp sa mạc cũng phải ngả mũ chào thua cơn cuồng phong này!",
  "Ối ái chà chà, một cú nhá hàng khiến cả thế giới đua xe ngỡ ngàng!",
  "Thần tốc độ hiển linh ngay trên cung đường này rồi!",
  "Ai đó mau gọi cứu hỏa đến đây gấp kẻo mặt đường bốc cháy mất!",
  "Lạy trời lạy phật, con mắt tôi vừa nhìn thấy điều kỳ diệu gì thế này?!",
  "Đừng chớp mắt, tôi nhắc lại là tuyệt đối không được chớp mắt một giây nào!",
  "Tiếng pô xe nổ đanh thép như tiếng sấm sét rạch ngang bầu trời!",
  "Một nhát ga định mệnh, xé toạc không gian và thời gian!",
  "Khán giả đang ôm đầu không tin nổi vào mắt mình!",
  "Cực sốc luôn anh em ơi, màn trình diễn này xứng đáng triệu lượt chia sẻ!",
  "Không thể nào cản nổi cơn cuồng nộ từ khối động cơ V12 tăng áp kép này!",
  "Đúng là quái vật đường đua, bước vào là xác định nuốt chửng mọi rào cản!",
  "Cả triệu người xem trực tiếp đang đồng thanh gào thét phấn khích!",
  "Bàng hoàng, sửng sốt và chết lặng trước pha xử lý siêu thực!",
  "Một đường cua vẽ bằng lửa và khói trắng bốc cao ngút trời!",
  "Rợn hết cả tóc gáy, sởn gai ốc từ đầu đến chân!",
  "Đẳng cấp này thì đưa vào viện bảo tàng tốc độ trưng bày ngay!",
  "Tốc độ xé gió rít lên gầm rú như máy bay tiêm kích phản lực!",
  "Cơn địa chấn cấp mười hai vừa đổ bộ thẳng vào trung tâm trường đua!",
  "Lốc xoáy màu sắc lướt qua ống kính máy quay với vận tốc xé gió!",
  "Ngả mũ bái phục, một tay lái sinh ra để thách thức mọi quy luật vật lý!",
  "Ôi trời cao đất dày ơi, chạy thế này thì ai mà chịu thấu!",
  "Bùng nổ rồi anh em ơi, màn so tài lịch sử chính thức bắt đầu!",
  "Kinh hoàng tột độ, một pha thoát hiểm trong gang tấc chỉ vài milimet!",
  "Mặt đất rung chuyển rền vang theo từng nhịp pít-tông!",
  "Chết mê chết mệt với pha biểu diễn nghệ thuật tốc độ đỉnh cao này!",
  "Tôi đang run rẩy cả hai tay khi cầm micro tường thuật lại khoảnh khắc này!",
  "Không một kịch bản phim Hollywood nào có thể kịch tính hơn lúc này!",
  "Sức mạnh vô song, cỗ máy chiến tranh đang nghiền nát mọi chướng ngại vật!",
  "Một cú giật mình thót tim khiến người xem bay luôn cả điện thoại trên tay!",
  "Đây không còn là một cuộc đua xe nữa, đây là chiến tranh giữa các vì sao!",
  "Khí thế ngút trời, tiếng reo hò vang dội cả một góc trời!",
  "Thót tim đến tận phút chót, đúng là nghẹt thở từng nhịp thở!",
  "Sẵn sàng bùng cháy cùng siêu phẩm tốc độ vô tiền khoáng hậu này chưa anh em?!",
  "Đập tan mọi nghi ngờ, khẳng định ngôi vương tuyệt đối!",
  "Dòng máu tốc độ đang sôi sùng sục trong huyết quản!",
  "Cả mạng xã hội đêm nay chắc chắn sẽ phát sốt vì pha bóng này!",
  "Một đường đua, một định mệnh và một kẻ hủy diệt đích thực!",
  "Đạp ga lút sàn, không còn một chút do dự nào trong ánh mắt!",
  "Năng lượng xung kích cực đại đang lan tỏa khắp các góc máy quay!",
  "Màn trình diễn đỉnh cao khiến tất cả các chuyên gia F1 phải câm nín!",
  "Một pha xé toạc làn gió cuốn phăng mọi đối thủ bám đuổi!",
  "Đỉnh của chóp, không còn mỹ từ nào có thể lột tả trọn vẹn!",
  "Dữ dội hơn cả sóng thần đại dương cuộn trào vào đất liền!",
  "Một tuyệt kỹ lái xe thất truyền nay bất ngờ tái xuất giang hồ!",
  "Sức nóng trong buồng lái đang chạm ngưỡng 80 độ C!",
  "Những tràng pháo tay giòn giã rền vang khắp các khán đài!",
  "Cảm giác nghẹt thở đến từng miligiây trôi qua!",
  "Thế trận đảo chiều chớp nhoáng khiến người xem ngơ ngác ngỡ ngàng!",
  "Mũi tên bạc xé toạc bầu không khí lao thẳng về phía trước!",
  "Sát khí ngút ngàn toát ra từ đôi mắt của tay đua cự phách!",
  "Cả cầu trường nín thở trước thời khắc lịch sử!",
  "Một đường cong hoàn mỹ được khắc họa bằng vệt lốp cao su bốc khói!",
  "Không một giây ngơi nghỉ, áp lực khủng khiếp đè nặng lên từng vòng bánh!",
  "Trận chiến sống còn giữa những chiến thần tốc độ bậc nhất thế giới!",
  "Kịch tính đến nghẹt thở, hồi hộp từng tích tắc của đồng hồ bấm giờ!",
  "Quá tàn khốc, không có chỗ cho bất kỳ một sai lầm nhỏ nào!",
  "Hào quang của nhà vô địch đang rực sáng chói lòa cả màn ảnh!",
  "Vũ điệu tử thần trên mép vực thẳm tốc độ!",
  "Khi tiếng gầm của động cơ cất lên, mọi thanh âm khác đều phải lu mờ!",
  "Một nhát chém ngọt lịm vào không gian bao la!",
  "Vận may hay tài năng xuất chúng? Câu trả lời là tài năng thượng thừa!",
  "Tất cả các giác quan đều đang bị đánh thức ở cường độ cực đại!",
  "Chiếc xe lướt đi tựa bóng ma tốc độ thoắt ẩn thoắt hiện!",
  "Chiến tích hào hùng đang dần được viết nên trên từng dải nhựa đường!",
  "Không thể rời mắt khỏi màn hình dù chỉ trong nửa tích tắc!",
  "Hơi thở dồn dập, huyết áp tăng vọt theo từng cú tăng ga!",
  "Màn ảo thuật trên bốn bánh xe khiến cả thế giới ngả mũ!",
  "Đẳng cấp của một huyền thoại sống, mãi mãi trường tồn!",
  "Vút bay như đạn pháo rời khỏi nòng!",
  "Cơn ác mộng tồi tệ nhất của mọi đối thủ cùng đường đua!",
  "Và bây giờ, hãy chiêm ngưỡng khoảnh khắc định đoạt số phận chặng đua!"
];

// 2. MA TRẬN BỐI CẢNH & THỜI TIẾT ĐƯỜNG ĐUA (50 ENVIRONMENTS)
export const TRACK_ENVIRONMENTS: string[] = [
  "trên cung đường cao tốc Monza bốc khói khét lẹt dưới ánh nắng chói chang",
  "giữa khúc cua tử thần 90 độ phủ đầy vệt lốp đen sì",
  "dưới cơn mưa rào tầm tã khiến mặt đường trơn trượt như bôi mỡ",
  "xuyên qua đường hầm xuyên núi rền vang tiếng pô gầm rú như sấm",
  "trên đường đua ven biển lộng gió với những con sóng bạc đầu gầm gào",
  "giữa màn sương mù dày đặc rạng sáng che khuất tầm nhìn 5 mét",
  "trên dải đại lộ ánh sáng rực rỡ đèn neon huyền ảo",
  "giữa chảo lửa sa mạc cát vàng bốc hơi nóng hầm hập 45 độ C",
  "tại đoạn thẳng tử thần dài 2 cây số nơi kim tốc độ chạm nóc",
  "trên con dốc uốn lượn hình chữ S hiểm trở bậc nhất hành tinh",
  "ngay sát mép vực thẳm đá cheo leo không có rào chắn bảo vệ",
  "giữa vòng xoay khổng lồ với lực ly tâm ép chặt tài xế vào ghế lái",
  "trên cây cầu treo bắc qua eo biển gió giật rung lắc cả khung xe",
  "dưới ánh hoàng hôn đỏ rực như máu phản chiếu trên mặt kính chắn gió",
  "tại ngã tư giao nhau nghẹt thở nơi tử thần chực chờ",
  "giữa hàng ngàn ngọn đuốc cổ vũ bập bùng sáng rực hai bên đường",
  "trên mặt đường rải sỏi đá dăm lạo xạo bắn tung tóe gầm xe",
  "xuyên qua khu rừng rậm nhiệt đới với những góc cua che khuất tầm mắt",
  "ngay tại vạch phân làn đôi nơi hai cỗ máy tranh giành từng tấc đất",
  "dưới chân ngọn tháp ánh sáng cao chọc trời của thành phố tương lai",
  "trên đường đua trên cao nối liền các tòa cao ốc chọc trời",
  "giữa biển khói trắng xóa bốc lên từ những cú lết bánh điên cuồng",
  "tại cửa ngõ dẫn vào khúc cua tay áo chữ U huyền thoại",
  "ngay trên đoạn đường gồ ghề khiến chiếc xe nảy bổng cả bốn bánh",
  "giữa cơn bão tuyết mịt mù phủ trắng từng cen-ti-mét mặt đường",
  "trên cung đường băng giá trơn như gương đòi hỏi kỹ năng thượng thừa",
  "xuyên qua thung lũng đá vôi vang vọng tiếng động cơ rền rĩ",
  "tại điểm giao nhau nguy hiểm nhất của giải đua Grand Prix",
  "ngay trước mũi xe đối thủ trên dải nhựa đường bốc hơi nóng",
  "giữa làn gió ngược cực mạnh thổi bạt cả cánh lướt gió sợi carbon",
  "trên đoạn đường uốn lượn liên hoàn không một giây ngơi nghỉ",
  "tại đỉnh dốc cao ngút ngàn nhìn xuống toàn cảnh đấu trường rực lửa",
  "giữa làn ranh mong manh giữa chiến thắng vinh quang và tai nạn thảm khốc",
  "trên mặt đường ướt sũng phản chiếu ánh đèn pha rực sáng",
  "ngay tại tâm bão của cuộc tranh tài nghẹt thở nhất năm",
  "dưới cơn mưa sao băng rực sáng trên nền trời đêm hoang dã",
  "tại khúc cua chữ S liên hoàn nơi các tay đua phải chuyển số điên cuồng",
  "trên đường thử nghiệm tối mật được trải nhựa siêu bám đường",
  "ngay tại góc mù hiểm hóc nơi mọi máy quay đều bị khuất góc",
  "giữa biển người hâm mộ cuồng nhiệt đang vẫy cờ rợp trời",
  "trên dải phân cách hẹp vừa khít đúng một thân xe siêu phẩm",
  "xuyên qua cánh đồng hoa hướng dương bát ngát rợp bóng cờ hoa",
  "tại cây số thứ 30 khi thể lực và lốp xe đã chạm ngưỡng giới hạn",
  "ngay dưới chân đài phun nước hoành tráng giữa quảng trường trung tâm",
  "trên đoạn đường dốc nghiêng 45 độ như lòng chảo lượn sóng",
  "giữa bức tường bê tông kiên cố và rào chắn kim loại tóe lửa",
  "tại điểm check-in sinh tử của chặng đua đường phố danh giá",
  "trên đại lộ hoàng gia thênh thang ngập tràn hoa giấy rực rỡ",
  "ngay bên cạnh cột mốc giới hạn tốc độ bị gió lốc quật ngã",
  "giữa không gian tĩnh lặng chết chóc trước khi tiếng nổ động cơ vang lên"
];

// 3. MA TRẬN KỸ THUẬT & PHONG THÁI TÁC CHIẾN (60 TACTICAL FLAVORS)
export const TACTICAL_FLAVORS: string[] = [
  "với phong thái lạnh lùng như một sát thủ máu lạnh",
  "bằng kỹ thuật vê côn giật số điệu nghệ đạt đến cảnh giới võ học",
  "với đôi bàn tay uyển chuyển múa lượn trên vành vô lăng sợi carbon",
  "nhờ vào khả năng đọc đường đua siêu việt không góc chết",
  "bằng một cú nhấp nhả phanh chuẩn xác đến từng phần nghìn giây",
  "với phản xạ thần kinh nhanh hơn cả xung điện não bộ",
  "bằng chiến thuật ép góc hiểm hóc khóa chặt mọi đường tẩu thoát",
  "với sự lì lợm và bản lĩnh thép không hề biết sợ hãi",
  "bằng cú đè chân ga dứt khoát không một milimet do dự",
  "với ánh mắt sắc lẹm khóa chặt mục tiêu phía trước",
  "nhờ vào sự ăn ý tuyệt đối giữa người lái và cỗ máy chiến mã",
  "bằng kinh nghiệm từng trải qua hàng trăm trận chiến sinh tử",
  "với độ tập trung cao độ đến mức nhịp tim gần như phẳng lặng",
  "bằng kỹ thuật bẻ lái ngược chống lật xe xuất thần",
  "với phong cách lái ngổ ngáo đậm chất đường phố hoang dã",
  "bằng sự khôn ngoan lọc lõi của một cáo già trường đua",
  "với lòng dũng cảm dám đặt cược tất cả vào một canh bạc tốc độ",
  "bằng cú lắc hông xe điệu nghệ né tránh chướng ngại vật trong tích tắc",
  "với kỹ năng kiểm soát độ trượt bánh đỉnh cao không tì vết",
  "bằng chiến thuật núp gió phục kích bài bản như sách giáo khoa quân sự",
  "với tư duy chiến thuật đỉnh cao đọc vị từng nước đi của đối thủ",
  "bằng một cú chuyển số mượt mà không hề làm tụt vòng tua máy",
  "với độ chuẩn xác tuyệt đối tựa một con robot lập trình tinh vi",
  "bằng sự liều lĩnh đến điên rồ khiến ai nấy đều phải thót tim",
  "với phong thái ngạo nghễ của một vị quân vương không ngai",
  "bằng kỹ năng ghì chặt vô lăng chống lại lực G-force xé rách cơ bắp",
  "với cú đánh lái chớp nhoáng nhanh như chớp giật giữa trời quang",
  "bằng sự điềm tĩnh lạ kỳ giữa chảo lửa hỗn chiến",
  "với nguồn năng lượng bùng nổ như núi lửa phun trào nham thạch",
  "bằng những cú nhấp nháy đèn pha gây áp lực tâm lý cực nặng",
  "với lối chạy xe hoang dại như một con mãnh thú săn mồi",
  "bằng cú hãm phanh trễ rợn người ngay trước vạch báo tử",
  "với đường cua hình học chuẩn xác đến từng mi-li-mét",
  "bằng đòn nghi binh giả vờ lách trái rồi bất ngờ phóng vút sang phải",
  "với kỹ thuật ghìm đầu xe bám chặt mặt đường như gắn nam châm",
  "bằng bản năng săn mồi thượng thừa ngửi thấy mùi chiến thắng từ xa",
  "với kỹ năng cân bằng trọng tâm xe bằng chân ga thần thánh",
  "bằng cú nhả côn bốc đầu xe lao vút đi như mũi tên săn",
  "với khả năng tính toán quỹ đạo bay của xe siêu việt",
  "bằng một cú xoay vô lăng 360 độ điệu nghệ đến ngỡ ngàng",
  "với sự lạnh lùng tàn nhẫn không chừa một khe hẹp nào cho đối thủ",
  "bằng kinh nghiệm đổ đèo trứ danh không ai sánh bằng",
  "với phong thái tự tin tuyệt đối như đang dạo chơi trong vườn nhà",
  "bằng cú búng côn tạo đà bứt phá không thể cản phá",
  "với kỹ năng căn khoảng cách chuẩn từng mi-li-mét với rào chắn",
  "bằng sự nhẫn nại rình rập chờ đợi sai lầm nhỏ nhất của con mồi",
  "với nguồn cảm hứng bất tận truyền từ tiếng gầm của động cơ",
  "bằng những cú bứt tốc bất thình lình khiến đối phương trở tay không kịp",
  "với nghệ thuật điều phối luồng gió khí động học quanh thân xe",
  "bằng nhãn quan chiến thuật bao quát toàn bộ 360 độ chiến trường",
  "với kỹ năng ôm cua lòng trong cướp góc cua ngoạn mục",
  "bằng những cú rà thắng điệu nghệ tạo vệt khói thơm mùi cao su",
  "với sự dẻo dai phi thường của một chiến binh bất khuất",
  "bằng pha xử lý đánh lừa trọng tài và khán giả một cách hoàn hảo",
  "với cú đảo làn liên hoàn khiến đối thủ hoa mắt chóng mặt",
  "bằng sức mạnh cơ bắp ghì chặt cần số titan nguyên khối",
  "với ý chí chiến đấu kiên cường không chịu khuất phục trước nghịch cảnh",
  "bằng phong cách đua xe biểu diễn đậm chất nghệ thuật đường phố",
  "với những pha drift song song đẹp như một cặp vũ công lướt trên băng",
  "bằng đòn kết liễu hoàn hảo khép lại mọi hy vọng lật kèo của đối thủ"
];

// 4. DANH SÁCH 35 SIÊU SAO, MEME, CẦU THỦ, HUYỀN THOẠI & STREAMER
export const EXTENDED_DRIVER_PROFILES: Record<string, DriverCommentaryProfile> = {
  'Cristiano Ronaldo': {
    name: 'Cristiano Ronaldo',
    aliases: ['Anh Bảy CR7', 'Siêu sao Cristiano Ronaldo', 'Cỗ máy ghi bàn CR7', 'Anh Bảy đại đế', 'Chàng trai Madeira', 'Chiến thần số 7'],
    signatureGag: 'ôm cua rồi bứt tốc hô vang Siuuuuu chấn động cả vũ trụ',
    shoutout: 'Siuuuu! Đẳng cấp mãi mãi là vĩnh cửu, không ai có thể cản bước anh Bảy!'
  },
  'Lionel Messi': {
    name: 'Lionel Messi',
    aliases: ['M10 El Pulga', 'Huyền thoại Lionel Messi', 'Bọ chét nguyên tử', 'Phù thủy sân cỏ M10', 'Bậc thầy xử lý GOAT', 'Thánh lừa bóng Rosario'],
    signatureGag: 'lắc hông xe bẻ lái mượt mà qua khe hẹp như đi dạo trong công viên',
    shoutout: 'Đỉnh cao ma thuật của M10, chỉ có thể ngả mũ chào thua thiên tài bóng đá!'
  },
  'Kylian Mbappe': {
    name: 'Kylian Mbappe',
    aliases: ['Ninja Rùa Mbappe', 'Cơn lốc đường biên Kylian', 'Siêu tốc độ Donatello', 'Vua tốc độ nước Pháp', 'Tia chớp Paris'],
    signatureGag: 'nhấn ga một cái xe phóng vút đi như máy bay tiêm kích phản lực',
    shoutout: 'Tốc độ xé gió của Ninja Rùa, chạy thế này thì ai mà đuổi kịp được em trai!'
  },
  'Erling Haaland': {
    name: 'Erling Haaland',
    aliases: ['Robot hủy diệt Haaland', 'Quái vật Na Uy', 'Cỗ xe tăng bọc thép Erling', 'Kẻ săn bàn Viking', 'Tàu hỏa bọc thép Na Uy'],
    signatureGag: 'càn quét thẳng qua làn xe đối thủ như một cỗ xe tăng không gì ngăn cản',
    shoutout: 'Sức mạnh hủy diệt của người máy Bắc Âu, nghiền nát mọi chướng ngại vật!'
  },
  'Max Verstappen': {
    name: 'Max Verstappen',
    aliases: ['Super Max', 'Mãnh thú Hà Lan Verstappen', 'Vua F1 Max Điên', 'Đương kim vô địch Verstappen', 'Cỗ máy bất khả chiến bại'],
    signatureGag: 'ép cua sát mép vỉa rào chắn với độ hung hãn tuyệt đối của sư tử Hà Lan',
    shoutout: 'Super Max! Chạy như thế này thì chức vô địch thế giới lại nằm gọn trong tay!'
  },
  'Lewis Hamilton': {
    name: 'Lewis Hamilton',
    aliases: ['Sir Lewis Hamilton', 'Huyền thoại 7 lần vô địch LH44', 'Hiệp sĩ xứ sương mù', 'Bậc thầy lốp xe Hamilton', 'Tay lái kỳ cựu F1'],
    signatureGag: 'điều khiển cỗ máy Mercedes lướt đi êm ái nhưng đầy uy lực chết người',
    shoutout: 'Still We Rise! Đẳng cấp của 7 lần vô địch thế giới vẫn sáng ngời trên đường đua!'
  },
  'Neymar Jr': {
    name: 'Neymar Jr',
    aliases: ['Ảo thuật gia Samba Neymar', 'Vũ công bãi biển Neymar Jr', 'Hoàng tử bóng đá Brazil', 'Neymar Santos', 'Bậc thầy quẩy đuôi xe'],
    signatureGag: 'đảo làn lượn sóng nhấp nhả ga điệu nghệ như một vũ điệu Samba Brazil',
    shoutout: 'Nét quyến rũ chết người của bóng đá nghệ thuật biểu diễn trên bốn bánh xe!'
  },
  'David Beckham': {
    name: 'David Beckham',
    aliases: ['Quý ông David Beckham', 'Đôi chân cong số 7 Beckham', 'Soái ca sân cỏ Becks', 'Biểu tượng thời trang & tốc độ', 'Thánh tạt cánh Old Trafford'],
    signatureGag: 'vẽ một đường cong cầu vồng hoàn mỹ qua góc cua sắc sảo như đường tạt bóng',
    shoutout: 'Chính xác đến từng milimet, đường cong uốn lượn mang thương hiệu Beckham!'
  },
  'Ronaldinho': {
    name: 'Ronaldinho',
    aliases: ['Rô Vẩu nụ cười Samba', 'Ảo thuật gia Ronaldinho Gaucho', 'Phù thủy nụ cười', 'Huyền thoại lừa bóng Camp Nou', 'Bậc thầy Flip-Flap'],
    signatureGag: 'vừa ôm cua vừa ngoác miệng cười tươi rói vẫy tay chào khán giả',
    shoutout: 'Bóng đá là niềm vui, đua xe là đam mê! Nụ cười Ronaldinho thắp sáng cả khán đài!'
  },
  'Ronaldo De Lima': {
    name: 'Ronaldo De Lima',
    aliases: ['Người ngoài hành tinh R9', 'Rô béo huyền thoại', 'Chân sút không thể ngăn cản R9', 'Sát thủ vùng cấm địa', 'Huyền thoại World Cup 2002'],
    signatureGag: 'bứt tốc đảo chân đảo bánh xe biến đối thủ thành những gã hề trên đường đua',
    shoutout: 'Người ngoài hành tinh đã đổ bộ! Không một hậu vệ hay tay đua nào có thể cản nổi R9!'
  },
  'Zlatan Ibrahimovic': {
    name: 'Zlatan Ibrahimovic',
    aliases: ['Đấng Ibra', 'Vị thần Zlatan Ibrahimovic', 'Sư tử Thụy Điển', 'Chúa tể tự phong Ibra', 'Chiến binh Taekwondo Zlatan'],
    signatureGag: 'tạt đầu xe đối phương kèm theo ánh nhìn coi thường như nhìn kiến bò',
    shoutout: 'Đường đua không tạo ra Zlatan, mà Zlatan tạo ra đường đua này cho anh em chạy ké!'
  },
  'Sơn Tùng M-TP': {
    name: 'Sơn Tùng M-TP',
    aliases: ['Chủ tịch Sơn Tùng M-TP', 'Hoàng tử mưa Tùng M-TP', 'Chàng trai Thái Bình', 'Chủ tịch Sky Tùng', 'Thần tượng âm nhạc M-TP'],
    signatureGag: 'bật nhạc Lạc Trôi phiêu theo từng nhịp ga bay bổng giữa tầng mây',
    shoutout: 'Nơi này có anh! Đẳng cấp của Chủ tịch khiến hàng triệu Sky vỡ òa tự hào!'
  },
  'Độ Mixi': {
    name: 'Độ Mixi',
    aliases: ['Tộc trưởng Độ Mixi', 'Lươn Thanh Độ', 'Tộc trưởng Cao Bằng', 'Đội trưởng Bộ Tộc MixiGaming', 'Chiến thần tấu hài Tày'],
    signatureGag: 'vừa ghì vô lăng vừa bấm còi bim bim gào lên kêu gãy mẹ cả ghế lái',
    shoutout: 'Hợp lý! Bộ tộc MixiGaming điểm danh ngay dưới bình luận, quá cháy anh Độ ơi!'
  },
  'Faker': {
    name: 'Faker',
    aliases: ['Quỷ vương bất tử Faker', 'Thánh Lee Sang-hyeok', 'Huyền thoại T1 Faker', 'Đấng tối cao Esports', 'Bậc thầy căn góc chết'],
    signatureGag: 'né cua né đòn né húc chuẩn xác 100% như tool né chiêu hack não đối thủ',
    shoutout: 'Tất cả các con đường đều dẫn về với Quỷ vương! Faker vẫn là một tượng đài vĩ đại!'
  },
  'IShowSpeed': {
    name: 'IShowSpeed',
    aliases: ['Troll thủ IShowSpeed', 'Thánh gầm gừ Speed', 'Fan cuồng số 1 của CR7', 'Thánh hú hét Speed', 'Chiến thần húc cột điện'],
    signatureGag: 'gầm gừ sủa gâu gâu đập vỡ cả camera hành trình rồi nhấn lút chân ga',
    shoutout: 'Speed vừa sủa vừa chạy xe! Khán giả vừa ôm bụng cười vừa thót tim vì sợ tai nạn!'
  },
  'PewDiePie': {
    name: 'PewDiePie',
    aliases: ['Vua YouTube PewDiePie', 'Felix Kjellberg', 'Chủ tịch sàn diễn meme', 'Thủ lĩnh đội quân Bro Army'],
    signatureGag: 'thực hiện cú Brofist vào gương chiếu hậu rồi tăng tốc vượt qua đối thủ',
    shoutout: 'Bro Army muôn năm! PewDiePie vẫn giữ vững phong độ của một huyền thoại internet!'
  },
  'MrBeast': {
    name: 'MrBeast',
    aliases: ['Đại gia MrBeast', 'Jimmy Donaldson', 'Thánh thử thách triệu đô', 'Trùm giveaway xe sang'],
    signatureGag: 'vừa lái xe vừa rải tiền thưởng 100 ngàn đô la ra cửa sổ cho các xe bám đuổi',
    shoutout: 'Chiếc xe trị giá 5 triệu đô la này thuộc về ai chạy nhanh nhất! Đẳng cấp MrBeast!'
  },
  'Vin Diesel': {
    name: 'Vin Diesel',
    aliases: ['Dominic Toretto', 'Anh cả Vin Diesel', 'Trùm băng nhóm Fast & Furious', 'Chiến thần Vì Gia Đình', 'Toretto Dodge Charger'],
    signatureGag: 'gài số 7 nhấn nút Nitro NOS xịt lửa và lẩm bẩm vì gia đình là tất cả',
    shoutout: 'Tiền bạc có thể kiếm lại được, nhưng Gia Đình là mãi mãi! Toretto vô địch!'
  },
  'Takumi Fujiwara': {
    name: 'Takumi Fujiwara',
    aliases: ['Thánh đổ đèo Takumi', 'Truyền nhân tiệm đậu hũ Fujiwara', 'Tay lái AE86 huyền thoại', 'Quái kiệt đèo Akina'],
    signatureGag: 'vừa ôm cua vừa giữ cốc nước trên taplo không sánh một giọt nào ra ngoài',
    shoutout: 'Kỹ thuật đổ đèo rãnh nước của chiếc AE86 huyền thoại! Cả thế giới phải cúi đầu!'
  },
  'Lightning McQueen': {
    name: 'Lightning McQueen',
    aliases: ['Tia chớp Lightning McQueen', 'Số 95 huyền thoại', 'Kachow thần thánh', 'Quán quân Cúp Piston'],
    signatureGag: 'nghiêng xe hai bánh nháy mắt một phát hô vang Kachow sáng lóa',
    shoutout: 'Kachow! Nhanh như chớp, trôi như gió! Số 95 huyền thoại bất khả chiến bại!'
  },
  'Charles Leclerc': {
    name: 'Charles Leclerc',
    aliases: ['Chàng thơ Monaco Charles Leclerc', 'Tay đua số 1 Ferrari', 'Lord Perceval', 'Thái tử đỏ Ferrari'],
    signatureGag: 'đưa chiếc chiến mã đỏ Ferrari lướt qua góc cua hẹp với vẻ đẹp tựa tranh vẽ',
    shoutout: 'Forza Ferrari! Chàng trai Monaco đã chứng minh tài năng thiên bẩm của mình!'
  },
  'Lando Norris': {
    name: 'Lando Norris',
    aliases: ['Cậu bé vàng Lando Norris', 'Ngôi sao trẻ McLaren', 'Tay đua hài hước xứ sương mù', 'Chiến thần tiệc tùng Lando'],
    signatureGag: 'ôm cua cực ngọt rồi búng tay cười đùa trêu chọc các đàn anh F1',
    shoutout: 'Lando Norris tiếp tục thăng hoa! Thế hệ trẻ F1 đang viết lại lịch sử tốc độ!'
  },
  'Fernando Alonso': {
    name: 'Fernando Alonso',
    aliases: ['Lão tướng Fernando Alonso', 'El Nano quái kiệt', 'Cáo già Tây Ban Nha Alonso', 'Nhà vô địch 2 lần F1'],
    signatureGag: 'phòng thủ góc cua kín kẽ đến mức một con kiến cũng không thể lọt qua',
    shoutout: 'Đẳng cấp cáo già trường đua! Tuổi tác chỉ là con số với quái kiệt Alonso!'
  },
  'Zinedine Zidane': {
    name: 'Zinedine Zidane',
    aliases: ['Huyền thoại Zizou', 'Bậc thầy Roulette Zidane', 'Gã đầu hói thiên tài', 'Đại tướng bóng đá Pháp'],
    signatureGag: 'xoay compa 360 độ thân xe quét sạch góc cua với sự tao nhã tuyệt đối',
    shoutout: 'Sự tao nhã và quý tộc của Zizou! Một pha quay xe đỉnh cao không tì vết!'
  },
  'Diego Maradona': {
    name: 'Diego Maradona',
    aliases: ['Cậu bé vàng Diego Maradona', 'Bàn tay của Chúa', 'Thánh đường bóng đá Napoli', 'Huyền thoại xứ Tango'],
    signatureGag: 'luồn lách qua 5 xe đối thủ liên tiếp như pha solo thế kỷ năm 1986',
    shoutout: 'Bàn tay của Chúa đã chạm vào vô lăng! Maradona bất tử trong lòng người hâm mộ!'
  },
  'Thierry Henry': {
    name: 'Thierry Henry',
    aliases: ['Đứa con của thần gió Henry', 'King Henry Arsenal', 'Sát thủ cứa lòng Thierry', 'Tia chớp Highbury'],
    signatureGag: 'lướt gió với sải bánh dài miên man cứa góc cua mượt mà như một nét vẽ',
    shoutout: 'Đúng là đứa con của thần gió! Bước chạy thanh thoát khiến tất cả phải ngước nhìn!'
  },
  'Khaby Lame': {
    name: 'Khaby Lame',
    aliases: ['Thánh đơn giản hóa Khaby Lame', 'Vua TikTok không lời', 'Thánh nhún vai Khaby', 'Biểu tượng tối giản toàn cầu'],
    signatureGag: 'không cần drift phức tạp chỉ cần chạy thẳng một đường rồi xòe hai tay ra nhún vai',
    shoutout: 'Đơn giản thế này mà các đối thủ cứ thích làm phức tạp lên! Khaby Lame đỉnh cao!'
  },
  'Soobin Hoàng Sơn': {
    name: 'Soobin Hoàng Sơn',
    aliases: ['Hoàng tử R&B Soobin', 'Anh trai tài hoa Soobin', 'Chiến thần visual sân khấu', 'Soobin SpaceSpeakers'],
    signatureGag: 'lái xe với phong thái lãng tử ngút ngàn làm tan chảy trái tim hàng triệu fan nữ',
    shoutout: 'Visual và kỹ năng đều đạt điểm tuyệt đối! Soobin cháy hết mình trên sân khấu tốc độ!'
  },
  'Ghost Rider': {
    name: 'Ghost Rider',
    aliases: ['Ma tốc độ Ghost Rider', 'Hiệp sĩ lửa địa ngục', 'Kẻ phán xét linh hồn', 'Chiến binh đầu lâu bốc lửa'],
    signatureGag: 'để lại hai dải lửa địa ngục bốc cháy rực rỡ thiêu đốt mặt đường nhựa',
    shoutout: 'Lửa địa ngục bùng cháy! Ma tốc độ đã trừng phạt mọi kẻ dám cản đường!'
  },
  'Trùm Cuối Vô Danh': {
    name: 'Trùm Cuối Vô Danh',
    aliases: ['Quái kiệt giấu mặt', 'Bóng ma đường đua số 99', 'Huyền thoại không tên', 'Sát thủ vô danh'],
    signatureGag: 'lặng lẽ xé gió lướt qua mọi siêu xe với nụ cười bí hiểm sau kính đen',
    shoutout: 'Không ai biết anh ấy là ai, nhưng ai cũng biết anh ấy là nhà vô địch thực thụ!'
  }
};

// 5. MA TRẬN 10 NHÓM HÀNH ĐỘNG CHI TIẾT (30 - 45 ACTIONS MỖI NHÓM)
export const MASSIVE_ACTIONS: Record<CommentaryCategory, string[]> = {
  START: [
    "đạp lút sàn chân ga, đầu xe nhấc bổng khỏi mặt đất bốc khói mù mịt",
    "nhả phanh tay chớp nhoáng, phóng vút lên dẫn đầu như một mũi tên xé gió",
    "bật hệ thống kiểm soát xuất phát Launch Control, cỗ máy lao đi không một độ trễ",
    "đốt cháy lốp xe tại chỗ tạo vệt cao su đen sì rồi bắn vọt về phía trước",
    "chớp thời cơ đèn đỏ vừa vụt tắt, cướp luôn làn đường ưu tiên của đối thủ",
    "phản xạ xuất phát thần tốc chỉ mất 0.12 giây, nhanh hơn cả cái chớp mắt",
    "gầm rú khối động cơ V12, âm thanh đanh thép nuốt chửng tiếng còi xuất phát",
    "phóng xe xé toạc làn khói trắng mở màn cho chặng đua khốc liệt",
    "lao đi như một con báo gấm săn mồi vừa được tháo cũi sổ lồng",
    "chiếm lĩnh ngay góc cua đầu tiên với cú bứt phá đầy quả quyết",
    "bung trọn công suất 1200 mã lực khiến cả trường đua rung chuyển dữ dội",
    "hất tung hàng ngàn mảnh cao su vụn về phía sau xe đối thủ",
    "đẩy vòng tua máy chạm ngưỡng 9000 RPM trước khi thả côn lao vút đi",
    "thực hiện màn đề-pa xuất thần làm lu mờ toàn bộ hàng xe xuất phát",
    "bứt tốc mạnh mẽ vượt qua hai xe bên cạnh ngay từ 50 mét đầu tiên",
    "dùng toàn lực ghì chặt vô lăng chống lại cú sốc gia tốc cực mạnh",
    "nhấp nhả côn điệu nghệ không để bánh xe bị trượt lãng phí một phần nghìn giây",
    "phát hỏa hai ống xả titan phía sau báo hiệu một cuộc thanh trừng tốc độ",
    "lao thẳng vào tâm bão bụi cát bỏ lại nhóm xe sau lưng trong ngỡ ngàng",
    "vọt lên như một quả hỏa tiễn rời bệ phóng lao thẳng vào không gian",
    "bật chế độ đua xe thể thao cực hạn giải phóng toàn bộ giới hạn tốc độ",
    "áp sát vạch phân làn trong giành lấy vị thế dẫn đầu đoàn đua",
    "cho cỗ máy gầm vang bài ca chiến trận kích thích mọi giác quan người xem",
    "lao đi với gia tốc từ 0 lên 200 km/h chỉ trong vòng vỏn vẹn hai giây rưỡi",
    "đè đầu cưỡi cổ các đối thủ nặng ký bằng màn đề-pa không tì vết",
    "khiến camera vạch xuất phát phải chao đảo vì luồng gió cuộn sau đuôi xe",
    "khởi đầu hoàn hảo tựa như những gì được lập trình trong máy tính giả lập",
    "mở màn chặng đua bằng một pha ra xe kinh điển ghi dấu ấn đậm nét",
    "phóng xe lướt trên mặt đường nhựa tựa một phi thuyền không trọng lực",
    "chiếm trọn spotlight ngay giây đầu tiên của cuộc đại chiến tốc độ"
  ],

  NITRO: [
    "nhấn nút Nitro Boost phản lực, ngọn lửa xanh lè phụt dài 2 mét sau ống xả",
    "kích hoạt hệ thống phun tăng áp Nitrous Oxide, xe bắn vọt đi với vận tốc âm thanh",
    "bơm toàn bộ bình Nitro kép, thân xe rung bần bật vì vượt ngưỡng gia tốc",
    "xả trọn luồng khí Nitro cực mạnh, kim đồng hồ tốc độ nhảy vọt thêm 80 km/h",
    "bật chế độ siêu tăng áp, xe phóng đi nhanh đến nỗi camera truyền hình bắt nét không kịp",
    "phụt lửa đỏ rực phía sau đuôi xe, tạo ra một luồng khí cuộn trào quét sạch cát bụi",
    "kích hoạt Nitro tầng hai, cỗ máy rít lên tiếng thét chói tai của loài thú dữ",
    "bung hết dung lượng bình Nitro cuối cùng trong canh bạc tất tay nghẹt thở",
    "đốt cháy hỗn hợp nhiên liệu đặc biệt, để lại dải lửa sáng rực trên mặt đường",
    "ép động cơ hoạt động ở 120% công suất thiết kế, bỏ xa đối thủ cả một thân xe",
    "bắn ra tia lửa lách tách từ hệ thống xả titan khi áp suất Nitro đạt đỉnh",
    "khiến không khí xung quanh thân xe bị xé toạc tạo thành luồng sóng xung kích",
    "nhồi thêm một nhát Nitro cực độc ngay giữa đoạn dốc cao",
    "bứt phá với gia tốc kinh hoàng khiến người lái dính chặt lưng vào đệm ghế",
    "mở khóa toàn bộ giới hạn ECU, giải phóng cơn thịnh nộ của cỗ máy tăng áp",
    "phun lửa sáng lòa cả màn đêm trường đua trong tiếng vỗ tay rần rần",
    "biến chiếc xe thành một quả cầu lửa tốc độ xuyên thủng bức tường gió",
    "nhấn chìm bàn đạp ga kết hợp Nitro tạo nên pha bứt tốc không tưởng",
    "tận dụng cú kích Nitro đẩy tốc độ chạm mốc 600 km/h không thể tin nổi",
    "làm cho khung xe rung chuyển dữ dội dưới sức ép của luồng khí phản lực",
    "kích nổ bình tăng áp kép tạo ra cú giật sốc gia tốc nghẹt thở",
    "bật van xả Nitro làm bùng lên hai cột khói lam đẹp mắt như trong phim điện ảnh",
    "vọt qua mặt đối thủ như một bóng ma nhờ cú tiêm Nitro chuẩn xác",
    "châm ngòi cho quả bom tốc độ ẩn giấu bên trong khối động cơ siêu nạp",
    "thổi bay mọi rào cản cản trở bằng nguồn năng lượng tăng áp vô tận",
    "xé rách bầu không khí yên ắng bằng tiếng gầm rú man dại của luồng khí Nitro",
    "đẩy cỗ máy chạm đến ngưỡng vận tốc của máy bay chiến đấu",
    "tạo ra một dải sáng màu xanh neon ma mị kéo dài phía sau đuôi xe",
    "thổi bùng ngọn lửa nhiệt huyết trong buồng lái với cú boost ngoạn mục",
    "làm mặt đường nứt toác dưới áp lực khủng khiếp của đòn tăng tốc phản lực"
  ],

  DRIFT: [
    "giật phanh tay bẻ lái ngược 90 độ, đuôi xe quét một vòng cung bốc khói khét lẹt sát mép vỉa ba-ri-e",
    "ôm cua với góc nghiêng hoàn hảo, vệt lốp cao su in hằn đen sì trên mặt đường nhựa nóng bỏng",
    "drift một pha nghệ thuật đỉnh cao theo phong cách Tokyo Drift, thân xe trượt ngang đẹp mắt như tranh vẽ",
    "vê vô lăng điệu nghệ kiểm soát góc trượt hoàn hảo, không lệch dù chỉ nửa milimet khỏi tâm đường",
    "quét đuôi xe sát rạt hàng rào bảo vệ, tia lửa cọ xát bắn tung tóe như pháo hoa đêm giao thừa",
    "chuyển trọng tâm liên hoàn lướt qua góc cua chữ Z mượt mà êm ái như một vũ công ba-lê",
    "ôm cua góc chết với vận tốc điên rồ, lốp xe rít lên ken két gào khóc trong sự phấn khích của người xem",
    "thực hiện cú drift quét vỉa thần thánh, bụi đường bay mù mịt tạo nên khung cảnh điện ảnh ngoạn mục",
    "bẻ lái counter-steer điệu nghệ giữ chiếc xe trượt ngang 45 độ ở vận tốc 400 km/h",
    "khóa vi sai cầu sau, ép hai bánh sau trượt dài tạo nên làn sương khói trắng ngút ngàn",
    "lướt bánh nhẹ nhàng qua đỉnh cua apex với độ chính xác cơ học hoàn mỹ",
    "thực hiện kỹ thuật drift chạm rào rợn người làm rụng cả gương chiếu hậu",
    "khiến bốn bánh xe ma sát tạo nên bản giao hưởng rít lốp đầy mê hoặc",
    "quăng đuôi xe sang trái rồi giật mạnh sang phải hoàn thành cú lắc hông huyền thoại",
    "giữ thăng bằng trên sợi dây tơ mỏng manh giữa kiểm soát và mất lái hoàn toàn",
    "tạo nên một đường cong parabol tuyệt mỹ bằng khói trắng và tia lửa đỏ",
    "lết bánh trượt ngang qua mặt ba chiếc xe đối thủ đang giảm tốc ôm cua",
    "làm cho các nhiếp ảnh gia ven đường phải nhảy cẫng lên vì phấn khích",
    "ghì chặt vô lăng xoay vòng điêu luyện như đang biểu diễn xiếc trên mặt đất",
    "bẻ lái một góc cua tay áo hiểm hóc khiến đối phương chỉ biết há hốc mồm thán phục",
    "giữ vòng tua máy cực cao để duy trì độ trượt bánh mượt mà không bị tụt ga",
    "quét sạch cát bụi trên mép lề đường bằng cản sau sợi carbon",
    "thực hiện pha drift 360 độ ăn mừng ngay trước mũi xe nhóm bám đuổi",
    "lướt đi trên mặt đường trơn trượt với sự điềm tĩnh phi thường của bậc thầy drift",
    "vẽ nên một vòng cung lửa rực rỡ dưới ánh đèn pha đêm trường đua",
    "làm tan chảy lớp cao su bề mặt lốp xe thành từng vệt đen bóng loáng",
    "xoay đầu xe chỉ trong chớp mắt chuyển hướng tấn công chớp nhoáng",
    "trượt ngang thân xe qua mép vực thẳm chỉ cách lằn ranh tử thần một gang tay",
    "khiến người xem phải đứng tim vì độ liều lĩnh của cú quét đuôi xe",
    "khắc họa một kiệt tác drift xe sẽ còn được nhắc lại trong nhiều năm tới"
  ],

  OVERTAKE: [
    "lách người qua khe hẹp sát mép cỏ chỉ vừa khít thân xe, vượt mặt đối thủ trong một cái chớp mắt",
    "đảo làn chữ S chớp nhoáng, tạt đầu đối thủ để lại làn khói cay sè mắt kèm một cái vẫy tay chào thân ái",
    "chớp thời cơ đối thủ ôm cua rộng, luồn vào góc trong bứt tốc vượt lên dẫn đầu không một động tác thừa",
    "vượt mặt ngoạn mục ngay trước vạch báo cua, đối thủ chỉ biết trơ mắt đứng nhìn cản sau xa dần",
    "ra đòn quyết định ở khúc cua định mệnh, lách qua hai xe kẹp săng-uých khiến cả trường đua nổ tung",
    "đè vạch ngoài rồi đột ngột cắt mặt vào trong, một pha vượt xe xứng đáng được chiếu lại 100 lần",
    "nhấp nháy đèn pha xin đường rồi nhấn ga vượt qua nhẹ như một cơn gió thoảng qua đời nhau",
    "bắt bài hoàn toàn ý đồ phòng thủ của đối phương, ung dung vượt lên chiếm lấy vị trí dẫn đầu",
    "thọc sâu vào góc cua lòng trong, ép đối thủ phải nhả ga nhường đường trong ấm ức",
    "thực hiện pha vượt xe kép vượt qua liền hai đối thủ chỉ sau một cú lắc lái",
    "tận dụng tối đa khoảng trống nửa mét để luồn lách như một chú lươn đại tài",
    "chèn ép đối thủ sát mép rào chắn rồi ung dung đạp ga bỏ xa một đoạn dài",
    "đánh lừa đối phương bằng pha nhá phanh rồi bất ngờ thốc ga vượt qua ngoạn mục",
    "vượt mặt từ phía bên ngoài khúc cua với độ dũng cảm và vận tốc kinh hoàng",
    "cướp lấy làn đường tối ưu ngay trước mũi giày của nhà đương kim vô địch",
    "để lại đối thủ phía sau trong sự cay đắng tột cùng và bất lực hoàn toàn",
    "lướt qua xe phía trước nhanh như một tia chớp rạch ngang qua tầm mắt",
    "bóp nghẹt mọi cơ hội phản kháng của đối phương bằng pha tạt đầu sắc bén",
    "khiến đối thủ giật mình đạp phanh suýt chút nữa đâm thẳng vào rào chắn",
    "thể hiện đẳng cấp vượt trội bằng một pha vượt xe không thể chê vào đâu được",
    "tung đòn knock-out quyết định tước đoạt vị trí dẫn đầu một cách thuyết phục",
    "xuyên thủng bức tường phòng ngự kiên cố mà đối thủ đã dày công dựng lên",
    "vượt lên dẫn đầu trong tiếng hò reo vang dội như sấm sét của hàng vạn cổ động viên",
    "lách qua khe hẹp tử thần nơi không một tay đua tỉnh táo nào dám mạo hiểm",
    "cho đối phương ngửi trọn làn khói xe nồng nặc mùi cao su cháy khét",
    "nhấn chìm mọi hy vọng của kẻ bám đuổi bằng pha bứt tốc dũng mãnh",
    "vẽ nên một đường cong vượt mặt kinh điển đi vào sách giáo khoa đua xe",
    "vọt lên nhẹ nhàng tựa lông hồng khiến đối thủ ngơ ngác không hiểu chuyện gì vừa xảy ra",
    "chuyển làn dứt khoát không một chút run tay khẳng định vị thế số một",
    "hoàn thành cú vượt xe ngoạn mục nhất trong lịch sử các giải đấu Grand Prix"
  ],

  BATTLE: [
    "so kè từng cen-ti-mét bánh chạm bánh tóe lửa, hai cỗ máy chiến tranh gầm rú tranh giành từng tấc đất",
    "bám sát nhau như hình với bóng ở vận tốc 550 km/h, không ai chịu nhường ai dù chỉ nửa vòng bánh xe",
    "hai tay lái đại tài ăn miếng trả miếng liên tục, liên tục đảo làn cản đường nghẹt thở từng tích tắc",
    "cuộc chiến không khoan nhượng của hai gã khổng lồ tốc độ, tiếng động cơ gầm vang rúng động bầu trời",
    "bánh xe cọ xát vào nhau tóe lửa xè xè, một màn so găng căng thẳng tột độ khiến khán giả muốn ngưng thở",
    "so kè tay đôi nghẹt thở suốt từ đầu đoạn thẳng đến tận cửa góc cua tử thần",
    "ép nhau sát rạt mép tường bê-tông, chỉ cần sơ sẩy một li là cả hai cùng dắt tay nhau vào gara sửa chữa",
    "hai con quái vật kim loại so kè từng phần nghìn giây, cuộc đua đang nóng lên đến 1000 độ C",
    "hai chiếc xe chạy song song kề vai sát cánh như hai võ sĩ giác đấu thời La Mã",
    "không một khoảng trống nào bị bỏ phí, hai tay đua gầm ghè nhau từng mét đường nhựa",
    "màn rượt đuổi nghẹt thở khiến cả tổ trọng tài phải dán mắt vào từng khung hình quay chậm",
    "va chạm liên tiếp giữa hai cánh lướt gió sợi carbon bắn tung tóe những mảnh vụn đen",
    "cuộc đấu trí đỉnh cao giữa hai bộ óc chiến thuật sắc sảo bậc nhất làng đua xe",
    "đẩy nhau vào thế hiểm hóc nơi lòng can đảm và độ liều lĩnh sẽ quyết định kẻ thắng người thua",
    "hai khối động cơ gào thét thi thố sức mạnh cơ bắp không hồi kết",
    "màn so tài thế kỷ giữa hai trường phái đua xe đối lập hoàn toàn",
    "liên tục hoán đổi vị trí cho nhau sau từng khúc cua uốn lượn",
    "ép đối thủ vào góc chết nhưng kẻ kia vẫn ngoan cường chống trả không chịu đầu hàng",
    "tiếng kim loại cọ xát ken két làm thót tim hàng triệu khán giả đang theo dõi",
    "trận chiến một mất một còn không có chỗ dung thứ cho kẻ yếu bóng vía",
    "hai chiếc xe như hai mũi giáo lao thẳng vào nhau trong một trận chiến sinh tử",
    "căng thẳng leo thang đến đỉnh điểm khi cả hai cùng nhấn ga lao vào góc cua hẹp",
    "không ai chịu chớp mắt, không ai chịu nhả ga dù chỉ một phần mười giây",
    "cuộc đọ sức kinh điển gợi nhớ lại những trang sử vàng son của làng F1 thế giới",
    "màn rượt đuổi điên rồ khiến nhịp tim của bình luận viên nhảy múa loạn xạ",
    "hai cỗ máy như hòa vào làm một trong vũ điệu hủy diệt tốc độ cao",
    "giằng co từng tấc đất như hai con hổ dữ đang tranh giành lãnh địa săn mồi",
    "màn đối đầu tay đôi kịch tính đến mức các bình luận viên phải hét khản cả giọng",
    "liên tục cài bẫy nhau bằng những pha đảo làn và phanh trễ đầy toan tính",
    "cuộc đụng độ của những vì sao sáng nhất trên bầu trời tốc độ đương đại"
  ],

  SLIPSTREAM: [
    "núp sát đuôi xe phía trước hút trọn luồng gió động học, tích tụ áp lực chờ thời cơ bung lụa",
    "bám đuôi ở cự ly chỉ 50 centimet, tận dụng hiệu ứng núp gió slipstream để gia tăng vận tốc lên cực đại",
    "chui vào vùng chân không phía sau đối thủ, xe lướt đi nhẹ bẫng chuẩn bị cho cú phóng tên lửa vượt mặt",
    "hút trọn luồng khí cuộn sau đuôi, kim đồng hồ tốc độ nhích lên từng nấc từng nấc đầy đe dọa",
    "gối đầu vào cản sau của xe dẫn đầu, giảm tối đa sức cản không khí để tiết kiệm nhiên liệu và lốp",
    "núp gió hoàn hảo tựa như bóng ma bám riết lấy gót chân của đối phương",
    "tận dụng luồng xoáy khí động học kéo chiếc xe lao đi vun vút với vận tốc không tưởng",
    "ẩn mình sau lưng kẻ thù như một xạ thủ bắn tỉa đang nín thở chờ con mồi sơ hở",
    "hút gió tăng tốc đẩy áp lực động cơ lên mức tối đa sẵn sàng cho cú bứt phá tử thần",
    "bám dính như keo dán sắt vào đuôi xe phía trước khiến đối thủ toát mồ hôi hột",
    "thu hẹp khoảng cách từng cen-ti-mét một nhờ vào kỹ thuật núp gió bậc thầy",
    "lợi dụng luồng khí đuôi xe để làm mát két nước tản nhiệt chuẩn bị phản kích",
    "chiếc xe như được một bàn tay vô hình kéo vút về phía trước theo sau bóng xe đối thủ",
    "chờ đợi thời khắc vàng khi lực hút gió đạt cực đại để tung cú đánh quyết định",
    "bám sát sạt cản sau làm cho camera lùi của đối phương chỉ nhìn thấy mỗi lưới tản nhiệt",
    "sử dụng chiến thuật núp gió kinh điển để xóa tan khoảng cách hai giây bám đuổi",
    "giấu mình trong vùng áp suất thấp chuẩn bị cho pha tách làn bứt tốc ngoạn mục",
    "lướt đi êm ả không tốn một giọt mồ hôi nhờ vào sự dẫn đường của kẻ dẫn đầu",
    "tạo ra lực đẩy khí động học cực mạnh đẩy vòng tua máy lên mức kịch trần",
    "bám đuôi đến nghẹt thở khiến tài xế xe trước phải liên tục liếc nhìn gương chiếu hậu"
  ],

  COLLISION: [
    "va chạm tóe lửa tung tóe, gõ nhẹ vào cản sau cảnh cáo đối thủ nhưng vẫn giữ vững tay lái thần sầu",
    "cọ xát cản trước vào thành rào chắn bắn pháo hoa rực rỡ nhưng cỗ máy bọc thép vẫn lao đi vun vút",
    "pha va chạm nảy lửa làm vỡ vụn sợi carbon khí động học, nhưng ý chí chiến thắng vẫn rực cháy nguyên vẹn",
    "thân xe va vào nhau kêu một tiếng chát chúa, cả hai tay đua vẫn lạnh lùng ghì chặt vô lăng tiếp tục cuộc chiến",
    "húc tung cọc tiêu giới hạn đường đua, bụi đất bay mù mịt nhưng chiếc xe vẫn băng băng tiến về phía trước",
    "cú chạm bánh rợn người làm chiếc xe chao đảo dữ dội nhưng tài xế đã cứu lái ngoạn mục",
    "va quẹt sườn xe làm móp méo lớp vỏ kim loại nhưng không thể làm giảm đi một km/h tốc độ",
    "cọ xát vào rào chắn bê tông phát ra âm thanh ken két rợn người làm rung chuyển cả buồng lái",
    "pha va chạm bánh chạm bánh khiến chiếc xe suýt chút nữa bay bổng lên không trung",
    "đập cản trước vào thành chắn lốp xe nhưng cỗ máy chiến tranh vẫn gầm rú lao đi",
    "màn so găng tóe lửa rực sáng cả một khúc cua u tối trong tiếng la ó của khán giả",
    "cú tông nhẹ mang tính chiến thuật làm đối phương mất thăng bằng lạng tay lái",
    "thân xe va đập liên hồi như hai chiếc tàu bọc thép đại chiến giữa biển khơi",
    "bắn ra hàng ngàn mảnh vụn sợi carbon lấp lánh dưới ánh đèn pha trường đua",
    "va chạm nghẹt thở nhưng bản lĩnh thép của nhà vô địch đã giúp chiếc xe trụ vững trên mặt đường",
    "cú huých hông đầy uy lực đẩy đối thủ ra sát mép rào cát giảm tốc",
    "tiếng kim loại vỡ vụn hòa cùng tiếng gầm động cơ tạo nên khung cảnh hỗn chiến điên cuồng",
    "pha đụng độ kinh hoàng làm rơi rụng cánh gió sau nhưng chiếc xe vẫn lao đi như mũi tên",
    "cú cọ xát nảy lửa thót tim làm rụng rời tay chân những khán giả yếu tim nhất",
    "sức chịu đựng phi thường của cỗ máy bọc thép giúp tay đua vượt qua cơn bão táp va chạm"
  ],

  FINISH: [
    "lao qua vạch đích đầu tiên với vận tốc âm thanh xé toạc lá cờ caro ca khúc khải hoàn",
    "cán đích vẻ vang giật cúp vô địch trong tiếng hò reo cuồng nhiệt như sấm dậy của hàng vạn cổ động viên",
    "về nhất thuyết phục tuyệt đối bỏ xa nhóm bám đuổi cả một đoạn đường dài bất tận",
    "xé gió lao qua cổng chào vinh quang, khắc tên mình lên đỉnh cao lịch sử trường đua danh giá",
    "cán vạch đích nghẹt thở với khoảng cách chỉ vỏn vẹn một phần trăm giây, giật trọn huy chương vàng danh giá",
    "về đích số một, chiếc xe lết bánh ăn mừng xoay tròn tạo thành những vòng khói trắng tuyệt mỹ",
    "hoàn thành chặng đua huyền thoại với kỷ lục thời gian mới không ai có thể xô đổ",
    "giật cúp vô địch trong sự ngỡ ngàng và thán phục tuyệt đối của tất cả các đối thủ sừng sỏ",
    "băng qua vạch đích như một vị hoàng đế trở về sau cuộc viễn chinh đại thắng",
    "cắt băng khánh thành chiến thắng lịch sử trong tiếng pháo hoa rợp trời và hoa giấy tung bay",
    "bỏ lại toàn bộ khói bụi và đối thủ phía sau, chạm tay vào chiếc cúp vàng danh giá",
    "về đích với tư thế hiên ngang ngẩng cao đầu của một huyền thoại bất khả chiến bại",
    "đăng quang ngôi vương giải đấu một cách xứng đáng sau những nỗ lực phi thường",
    "hoàn tất cú hat-trick chiến thắng liên tiếp khiến cả thế giới đua xe phải ngả mũ bái phục",
    "cán vạch đích vinh quang trong niềm xúc động nghẹn ngào của toàn thể đội ngũ kỹ thuật",
    "chiến thắng nghẹt thở ở những mét cuối cùng khép lại một chặng đua kịch tính nhất lịch sử",
    "lao vút qua đích như một con đại bàng sải cánh bay vào đại lộ vinh quang rực rỡ",
    "thổi bùng bữa tiệc ăn mừng chiến thắng hoành tráng nhất từ đầu mùa giải đến nay",
    "giương cao lá cờ chiến thắng trong tiếng reo hò không ngớt của biển người hâm mộ",
    "chính thức bước lên bục podium cao nhất nhận chiếc cúp vô địch danh giá bậc nhất thế giới",
    "kết thúc chặng đua hoàn hảo không một tì vết với điểm số tuyệt đối từ ban giám khảo",
    "ghi tên mình vào ngôi đền của những huyền thoại tốc độ vĩ đại nhất mọi thời đại",
    "cán đích đầu tiên khẳng định vị thế độc tôn không ai có thể lay chuyển trên đường đua",
    "đem về vinh quang chói lọi cho đội đua sau những ngày tháng miệt mài khổ luyện",
    "về nhất trong sự tôn trọng và khâm phục tuyệt đối của toàn bộ đối thủ trên đường chạy",
    "xé toạc mọi giới hạn thời gian thiết lập nên chuẩn mực mới cho môn thể thao tốc độ",
    "hoàn thành sứ mệnh lịch sử đưa chiếc siêu xe vinh quang bước lên đỉnh cao thế giới",
    "chạm đích đầu tiên và thực hiện màn đốt lốp ăn mừng cháy rực cả một góc trường đua",
    "khép lại màn trình diễn siêu thực bằng chiến thắng giòn giã không thể chối từ",
    "bước lên đỉnh vinh quang giật trọn phần thưởng khổng lồ và sự ngưỡng mộ của muôn triệu con tim"
  ],

  LEADER: [
    "ung dung dẫn đầu đoàn đua với khoảng cách an toàn, làm chủ cuộc chơi từ đầu đến cuối",
    "dẫn đoàn xe xé gió băng băng về phía trước như một vị tướng lĩnh chỉ huy quân đoàn siêu xe",
    "bỏ lại toàn bộ khói bụi phía sau, một mình một ngựa băng băng trên đại lộ vinh quang",
    "kiểm soát hoàn toàn nhịp độ trận đấu, điều phối cuộc đua theo ý muốn của riêng mình",
    "giữ vững vị trí số một với phong thái ung dung đĩnh đạc của một bậc thầy đua xe",
    "bỏ xa kẻ bám đuổi thứ hai tới hơn 5 giây cách biệt, một khoảng cách mênh mông như đại dương",
    "thống trị tuyệt đối đường đua không cho bất kỳ kẻ nào có cơ hội áp sát",
    "dẫn đầu đoàn rước siêu xe với tốc độ ổn định đến mức đáng kinh ngạc",
    "lướt đi như một cánh chim đầu đàn dẫn lối cho cả bầy quái thú kim loại phía sau",
    "làm chủ mọi khúc cua và đoạn thẳng, biến đường đua thành sân khấu độc diễn của riêng mình",
    "vững vàng ở ngôi đầu bảng bất chấp mọi nỗ lực vùng vẫy bám đuổi của đối thủ",
    "tạo ra một khoảng cách an toàn tuyệt đối tựa như một bức tường thành bất khả xâm phạm",
    "lãnh đạo cuộc đua với sự lạnh lùng và bản lĩnh của một vị vua tốc độ đích thực",
    "chiếu sáng cả đường đua bằng ánh hào quang rực rỡ của kẻ dẫn đầu cô đơn",
    "ung dung ngắm nhìn các đối thủ phía sau đang chật vật so kè cấu xé lẫn nhau",
    "bảo vệ vị thế tiên phong bằng những vòng đua hoàn hảo không một sai sót",
    "thể hiện sức mạnh thống trị tuyệt đối khiến cả giải đua phải cúi đầu thán phục",
    "dẫn dắt cuộc chơi với sự tự tin ngút trời của một kẻ sinh ra để chiến thắng",
    "băng băng về phía trước như một mũi tên đã bắn đi không gì có thể níu giữ",
    "duy trì vị trí dẫn đầu một cách ngoạn mục qua từng chặng kiểm soát thời gian"
  ],

  CRASH_SAVE: [
    "suýt chút nữa thì toang nhưng pha cứu lái xuất thần đã giữ chiếc xe thăng bằng ngay trên mép vực thẳm",
    "bánh xe mất lái xoay vòng nhưng tay đua đã bình tĩnh giật số kéo phanh cứu sống cả mùa giải",
    "chiếc xe trượt dài bốc khói suýt đâm rào chắn nhưng cú bẻ lái ngược thần sầu đã cứu nguy ngoạn mục",
    "thót tim trong gang tấc khi thân xe nghiêng hẳn sang hai bánh rồi bất ngờ tiếp đất an toàn",
    "mất kiểm soát ở vận tốc 500 km/h nhưng bản lĩnh siêu phàm đã giật chiếc xe trở lại quỹ đạo",
    "pha xử lý thoát chết kỳ diệu khiến toàn bộ ban huấn luyện phải ôm ngực thở phào nhẹ nhõm",
    "bánh sau trượt khỏi mép cỏ lề đường nhưng cú vê ga xuất quỷ nhập thần đã kéo chiếc xe trở lại",
    "chiếc xe xoay 180 độ nhưng tài xế đã nhanh tay cài số lùi rồi quay đầu tiếp tục phóng đi",
    "suýt chút nữa biến cỗ máy triệu đô thành đống sắt vụn nhưng thần may mắn và tài năng đã mỉm cười",
    "pha cứu nguy để đời xứng đáng được phát đi phát lại trên mọi bản tin thể thao quốc tế",
    "giữ vững vô lăng trong tình huống ngàn cân treo sợi tóc không để xe bị lật nhào",
    "bẻ lái thoát hiểm trong tích tắc khi chiếc xe phía trước bất ngờ mất lái xoay tròn",
    "cú nhấp phanh ABS điêu luyện dập tắt nguy cơ đâm thẳng vào rào chắn bê tông",
    "lấy lại độ bám đường kỳ diệu sau khi bị hất tung cả bốn bánh lên không trung",
    "pha né tránh thần sầu khiến tử thần cũng phải lắc đầu ngao ngán bỏ đi",
    "bình tĩnh xử lý sự cố kẹt chân ga đưa chiếc xe lướt qua góc cua an toàn đến khó tin",
    "cứu sống cả một chiến dịch đua xe bằng phản xạ thần kinh của một siêu nhân đích thực",
    "thoát khỏi vụ tai nạn liên hoàn trong gang tấc chỉ cách vài milimet định mệnh",
    "chiếc xe trượt bánh như trên sân băng nhưng tài năng thượng thừa đã làm chủ tình thế",
    "một màn thoát hiểm ngoạn mục khiến cả khán đài phải đồng loạt đứng dậy vỗ tay tán thưởng"
  ]
};

// 6. MA TRẬN LÝ DO HÀI HƯỚC & KÈO CÁ CƯỢC VIRAL (100 FUNNY STAKES)
export const MASSIVE_FUNNY_STAKES: string[] = [
  "để kịp phóng về nhà nấu cơm tối kẻo bị vợ khóa cửa bắt ngủ ngoài hành lang!",
  "kiếm tiền thưởng nóng chuộc lại chiếc nhẫn kim cương bị cắm tạm ở tiệm cầm đồ!",
  "trả dứt điểm món nợ bát phở bò tái gầu thơm phức từ tuần trước chưa thanh toán!",
  "chạy trốn tổ tuần tra giao thông đang đứng chờ lập biên bản ở khúc cua phía trước!",
  "khao toàn thể 500 anh em trong xóm một chầu lẩu cá kèo no nê ngập răng!",
  "giành lấy bản hợp đồng quảng cáo dầu gội đầu trị giá 10 triệu đô la Mỹ!",
  "để chứng minh cho cả thế giới và cô người yêu cũ thấy ai mới là vua tốc độ thực thụ!",
  "chạy nhanh đến mức gió lốc thổi bay cả nón bảo hiểm lẫn kính râm của trọng tài!",
  "khiến máy bắn tốc độ của ban tổ chức bốc khói nổ tung vì nhảy số quá nhanh!",
  "làm cho các đối thủ phía sau chỉ biết ngậm ngùi hít khói cay xè mắt trong bất lực!",
  "khiến ban tổ chức phải cấp tốc gọi hai xe cứu hỏa vì mặt đường đang cháy rực!",
  "về đích xong phải chạy vội đi đón con kẻo cô giáo mầm non lại gọi điện mách bố mẹ!",
  "chạy như bị mẹ cầm chổi đuổi đằng sau, không có bất kỳ lý do gì để giảm tốc độ!",
  "để không phải rửa bát dọn nhà trong suốt một tháng tới theo kèo cá cược với đồng đội!",
  "chứng minh đẳng cấp xe mượn của bạn thân chạy còn bốc hơn cả xe của chính mình!",
  "kiếm tiền đổ đầy bình xăng đang chạm đáy chuông báo đỏ liên hồi!",
  "chạy nhanh hơn cả vận tốc người yêu cũ lật mặt khi chia tay!",
  "khiến toàn bộ các camera giám sát góc cua phải quay cuồng tìm bóng dáng xe!",
  "đáp lại lời thách đấu ngông cuồng của tay đua đối thủ vào tối hôm qua trên mạng xã hội!",
  "giữ vững danh hiệu tay lái lụa số một hành tinh không cho ai có cơ hội chạm vào!",
  "để tối nay tự tin livestream khoe cúp vàng với hàng triệu người hâm mộ!",
  "giành giải nhất lấy tiền mua tặng mẹ chiếc máy giặt sấy tự động đời mới!",
  "chạy như ma đuổi vì trót lỡ hẹn giờ ăn cơm với phụ huynh lúc 7 giờ tối!",
  "khiến mấy ông bình luận viên phải nuốt nước bọt ừng ực vì đọc tên không kịp!",
  "để không bị lũ bạn trong xóm bêu rếu là tay lái gà mờ suốt cả năm nay!",
  "giật cúp vàng về làm giải thưởng bốc thăm may mắn cho buổi họp lớp cuối năm!",
  "chạy bạt mạng để kịp giờ công chiếu bộ phim siêu bom tấn tại rạp chiếu phim!",
  "khao cả làng một chầu trà sữa trân châu full topping ngập tràn thạch phô mai!",
  "chứng minh cho ông hàng xóm thấy chiếc xe cỏ này cũng biết bay lượn trên đường!",
  "để trả thù mối hận bị đối thủ tạt đầu cướp mất bát canh cua ở chặng đua trước!",
  "chạy nhanh để gió thổi khô bộ quần áo vừa giặt vội chưa kịp phơi khô!",
  "kiếm tiền nâng cấp dàn loa sub siêu trầm nghe nhạc quẩy banh nóc nhà!",
  "để nhận được cái gật đầu đồng ý hẹn hò của cô nàng hot girl trường đua!",
  "chạy trốn đàn chó dữ vô tình xổng chuồng đuổi theo sát nút phía sau!",
  "để trở thành tay đua đầu tiên trong gia phả dòng họ được lên sóng truyền hình trực tiếp!",
  "chạy như bay để kịp mua vé ca nhạc của thần tượng vừa mở bán lúc 8 giờ sáng!",
  "làm cho đối thủ phải cay cú đập vỡ cả vô lăng mô phỏng ở nhà!",
  "để tối nay được quyền chọn kênh tivi mà không bị ai tranh giành điều khiển!",
  "chứng minh rằng tốc độ ánh sáng cũng chỉ là muỗi so với chiếc siêu xe này!",
  "giật lấy phần thưởng nóng là một chuyến du lịch Hawaii miễn phí trọn gói!",
  "chạy nhanh đến nỗi đồng hồ thông minh báo nhịp tim chạm ngưỡng báo động đỏ!",
  "để không phải đóng tiền phạt quỹ nhóm theo luật chơi của hội anh em thiện lành!",
  "chứng minh tài năng cho bố vợ tương lai thấy để được gả con gái cưng!",
  "chạy như một vị thần để kịp giờ nhận mã giảm giá 50% trên sàn thương mại điện tử!",
  "làm cho các chuyên gia dự đoán bóng đá và đua xe phải xé toạc bảng phân tích!",
  "để lấy lại chiếc áo khoác da hàng hiệu bị đối thủ cá cược lấy mất hôm qua!",
  "chạy bốc lửa để làm nóng bầu không khí đang bị đóng băng vì trời quá rét!",
  "kiếm tiền thưởng mua tặng em gái bộ máy tính gaming siêu khủng để học tập!",
  "chạy nhanh để vượt qua bóng tối của sự thất bại và chạm tay vào ánh sáng vinh quang!",
  "để chứng minh xe số sàn đời cũ vẫn có thể dạy cho xe số tự động một bài học nhớ đời!",
  "chạy như bị ong chích đằng sau đít, không dám ngoái đầu lại nhìn dù chỉ một giây!",
  "khiến tổ trọng tài phải họp khẩn cấp để xem có dùng tên lửa phản lực trái phép hay không!",
  "để trở thành nhân vật chính trong cuốn tự truyện tốc độ bán chạy nhất năm!",
  "chạy nhanh đến mức gió lốc hất tung cả tóc giả của ông giám đốc giải đua!",
  "kiếm đủ tiền để mở một quán cà phê ngắm xe đua cho thỏa niềm đam mê!",
  "chạy để xóa bỏ mọi kỷ lục cũ từng được thiết lập trong suốt 50 năm qua!",
  "để không phải ăn mì tôm trừ bữa trong suốt tuần lễ tiếp theo!",
  "làm cho các hãng siêu xe lớn nhất hành tinh phải xếp hàng xin tài trợ hợp đồng!",
  "chạy như một mũi tên rời cung, nhắm thẳng vào hồng tâm chiến thắng mà lao tới!",
  "để mang chiếc cúp vô địch về làm đồ chặn giấy cho bàn làm việc của bố mẹ!",
  "chứng minh cho đám antifan trên mạng xã hội thấy ai mới là nhà vua thực sự!",
  "chạy nhanh để kịp ship cốc cà phê nóng cho bạn gái trước khi bị nguội ngắt!",
  "khiến dàn âm thanh sân vận động muốn nổ tung vì phải phát đi phát lại bài ca chiến thắng!",
  "để tối nay được ngủ một giấc thật ngon không mộng mị sau những chuỗi ngày căng thẳng!",
  "chạy như một chiến binh Viking thực thụ, sẵn sàng ngã xuống trên đống lốp cao su!",
  "kiếm tiền thưởng mời cả ê-kíp kỹ thuật đi ăn thịt nướng buffet không giới hạn!",
  "chạy để trả lời cho câu hỏi: Ai là người nhanh nhất hành tinh này lúc này?!",
  "khiến các tay đua kỳ cựu khác phải ngậm ngùi viết đơn xin giải nghệ sớm!",
  "để được khắc tên mình bằng chữ mạ vàng trên đại lộ danh vọng thể thao!",
  "chạy nhanh hơn cả thời gian trôi qua trong những ngày nghỉ lễ cuối tuần!",
  "chứng minh rằng một khi đã lên xe thì không có khái niệm chạy chậm trong từ điển!",
  "để có cớ từ chối lời mời đi ăn cưới của người yêu cũ vào chủ nhật tuần này!",
  "chạy như thể ngày mai là ngày tận thế và đây là chuyến xe cuối cùng rời khỏi trái đất!",
  "khiến các kỹ sư trưởng của đối thủ phải ôm đầu gục ngã vì chiến thuật bị bẻ gãy!",
  "để được ăn mừng bằng cách tắm trong vòi phun rượu champagne đắt giá nhất thế giới!",
  "chạy bạt mạng vì nồi thịt kho hột vịt ở nhà đang sôi sùng sục sắp cạn nước!",
  "chứng minh với cả làng là mình không hề chém gió về khả năng lái xe thượng thừa!",
  "để giật giải nhất mang về làm quà cưới cho thằng bạn thân chí cốt!",
  "chạy nhanh đến mức camera vệ tinh ngoài vũ trụ cũng chụp được vệt khói xe!",
  "khiến mọi lời đàm tiếu vô căn cứ trước trận đấu đều biến thành tro bụi!",
  "để tối nay tự thưởng cho bản thân một suất mát-xa phục hồi cơ bắp toàn thân!",
  "chạy như một cơn lốc xoáy quét sạch mọi rào cản ngăn bước tới vinh quang!",
  "kiếm tiền thưởng làm một chuyến phượt xuyên lục địa trên chính cỗ máy chiến mã này!",
  "chạy để khẳng định rằng không có góc cua nào là không thể drift qua được!",
  "khiến cả thế giới phải nhắc đến tên mình trên trang nhất của mọi tờ báo lớn!",
  "để kết thúc một mùa giải đầy sóng gió bằng một nốt thăng rực rỡ nhất!",
  "chạy như thể bình xăng chứa đầy máu lửa và linh hồn của những huyền thoại!",
  "để không phải hối tiếc bất kỳ một giây phút nào sau khi bước xuống xe!",
  "làm cho người hâm mộ phải phát cuồng và khắc ghi khoảnh khắc này mãi mãi!",
  "chạy vì niềm tự hào dân tộc và màu cờ sắc áo đang tung bay trên nóc xe!",
  "chứng minh rằng giới hạn sinh ra là để bị phá vỡ bởi những kẻ dám ước mơ lớn!",
  "để biến giấc mơ thời thơ ấu trở thành hiện thực rực rỡ trước mắt hàng triệu người!",
  "chạy như chưa từng được chạy, cháy như chưa từng được cháy trong đời!",
  "khiến cho đối thủ truyền kiếp phải cúi đầu bắt tay chúc mừng trong sự tâm phục khẩu phục!",
  "để đem lại nụ cười rạng rỡ và những giọt nước mắt hạnh phúc cho người thân!",
  "chạy vì tình yêu bất diệt dành cho tiếng gầm rú của khối động cơ đốt trong!",
  "chứng minh rằng trong cuộc đua này, anh ấy mới chính là định mệnh của chiếc cúp vàng!",
  "chạy để ghi dấu một cột mốc chói lọi không thể phai mờ trong lịch sử thể thao nhân loại!",
  "và cuối cùng là để khẳng định: Đỉnh cao này là của riêng anh ấy, không ai có thể cướp đi!"
];

// 7. MA TRẬN PHẢN ỨNG KHÁN GIẢ & BÌNH LUẬN VIÊN & ĐỐI THỦ (60 AUDIENCE REACTIONS)
export const AUDIENCE_REACTIONS: string[] = [
  "Khán giả trên khán đài đồng loạt đứng bật dậy ném mũ ném áo ăn mừng điên loạn!",
  "Trọng tài chính trố tròn hai mắt, suýt chút nữa làm rơi chiếc còi vàng trên miệng!",
  "Bình luận viên đập bàn rầm rầm khiến micro suýt gãy làm đôi vì quá phấn khích!",
  "Đối thủ phía sau chỉ biết cắn móng tay hối hận vì một giây sơ sẩy đánh mất cả cơ đồ!",
  "Hàng vạn ống kính máy ảnh chớp nháy liên hồi tạo nên một dải ngân hà ánh sáng rực rỡ!",
  "Toàn bộ đội ngũ kỹ thuật trong pit-lane ôm chầm lấy nhau khóc nức nở vì xúc động!",
  "Người hâm mộ gào thét vang dội cả một góc trời như động đất cấp mười!",
  "Các chuyên gia phân tích F1 chỉ biết lắc đầu thốt lên hai từ kinh ngạc!",
  "Camera truyền hình bắt trọn khoảnh khắc đối thủ đập tay lên vô lăng cay cú!",
  "Tiếng kèn vuvuzela và tiếng trống rền vang như một ngày hội lớn của dân tộc!",
  "Khán giả truyền hình ở nhà chắc chắn đang nhảy cẫng lên khỏi ghế sô pha!",
  "Trưởng ban tổ chức phải tháo kính lau mồ hôi hột vì tốc độ quá kinh hoàng!",
  "Hàng ngàn chiếc cờ caro đen trắng đang vẫy rợp trời chào đón vị anh hùng!",
  "Đối thủ bị vượt mặt chỉ biết lắc đầu ngao ngán tự hỏi mình vừa gặp phải quái vật gì!",
  "Cả trường đua như nín thở theo dõi từng mét đường rồi vỡ òa trong tiếng hoan hô!",
  "Các tay đua kỳ cựu ngồi trong phòng chờ đều phải đứng dậy vỗ tay tán thưởng!",
  "Người xem trực tiếp trên mạng xã hội đang bão thả tim và bình luận nghẽn cả máy chủ!",
  "Tiếng reo hò cuồng nhiệt át đi cả tiếng động cơ gầm rú bên dưới đường đua!",
  "Mẹ của tay đua ở quê nhà đang lau những giọt nước mắt tự hào khi nhìn con trên tivi!",
  "Cả khán đài đang đồng thanh hô vang tên của người hùng tốc độ không ngớt!",
  "Các nhiếp ảnh gia quốc tế chen lấn xô đẩy để chớp lấy nụ cười của kẻ chiến thắng!",
  "Đối phương chỉ biết ngửa mặt lên trời than thở sao số phận trớ trêu đến thế!",
  "Khói màu và pháo sáng rực rỡ được thắp lên nhuộm đỏ cả một khoảng trời!",
  "Bình luận viên đối thủ phải cay đắng thừa nhận sự vượt trội tuyệt đối này!",
  "Những tràng pháo tay kéo dài không dứt như những đợt sóng biển dâng trào!",
  "Khán giả đang ôm đầu không tin nổi vào mắt mình trước pha xử lý vi diệu!",
  "Một bầu không khí cuồng nhiệt chưa từng có trong lịch sử các kỳ giải đấu!",
  "Các tay đua bị loại sớm chỉ biết đứng bên lề đường vỗ tay chúc mừng kẻ mạnh nhất!",
  "Những tiếng huýt sáo tán thưởng vang lên rộn rã từ khắp bốn phương tám hướng!",
  "Một làn sóng cảm xúc mãnh liệt cuốn phăng đi mọi sự mệt mỏi của người xem!",
  "Toàn bộ khán phòng bình luận quốc tế đều đồng loạt thốt lên tiếng trầm trồ bái phục!",
  "Đối thủ bám đuổi đã buông xuôi hai tay chấp nhận số phận an bài!",
  "Người hâm mộ đang tràn xuống sát hàng rào để được nhìn ngắm thần tượng gần hơn!",
  "Biển người đang nhảy múa ca hát tưng bừng như lễ hội carnival đường phố!",
  "Cả mạng internet đang nổ tung với hàng triệu lượt tìm kiếm tên tuổi của tay đua!",
  "Ánh mắt thán phục của các đồng nghiệp nói lên tất cả về giá trị của pha bóng này!",
  "Một cảm giác rùng mình xúc động lan tỏa khắp cơ thể của mọi tín đồ tốc độ!",
  "Khán đài VIP nơi các tỷ phú ngồi cũng không giấu nổi sự phấn khích tột cùng!",
  "Tiếng hò reo cổ vũ như tiếp thêm đôi cánh vô hình cho chiếc xe xé gió lao đi!",
  "Không khí nghẹt thở kéo dài suốt chặng đua cuối cùng đã vỡ òa trong men say chiến thắng!",
  "Mọi hoài nghi, mọi chỉ trích đều đã bị dập tắt hoàn toàn bởi sự thật hiển nhiên này!",
  "Các huấn luyện viên đối thủ chỉ biết khoanh tay lắc đầu trước sự chênh lệch đẳng cấp!",
  "Người ta sẽ còn kể cho con cháu nghe về buổi chiều lịch sử ngày hôm nay trên trường đua!",
  "Cơn mưa hoa giấy lấp lánh phủ kín nóc xe như vương miện trao tặng nhà vua mới!",
  "Khán giả trẻ tuổi đang phát cuồng nhảy múa ăn mừng theo phong cách thần tượng!",
  "Một ngày thi đấu sẽ đi vào huyền thoại và khắc sâu trong tâm trí mọi người mãi mãi!",
  "Những nụ cười rạng rỡ và những cái ôm siết chặt giữa các thành viên đội đua!",
  "Tiếng nổ vang rền của những chai sâm-panh báo hiệu một đêm không ngủ sắp bắt đầu!",
  "Đối thủ cay đắng nhận ra rằng mình vừa chạm trán một thế lực không thể đánh bại!",
  "Một tràng pháo tay bất tận tôn vinh tinh thần thể thao cao thượng và tài năng trác tuyệt!",
  "Khán giả đứng ngồi không yên, hò reo đến khản cả giọng mà vẫn muốn hét to hơn nữa!",
  "Mọi ống kính truyền hình đều tập trung vào đôi mắt ngập tràn niềm kiêu hãnh của nhà vô địch!",
  "Một khoảnh khắc thiêng liêng khiến cả trường đua như lắng lại trong giây lát trước khi bùng nổ!",
  "Tiếng hô vang dội như muốn xé toạc bầu trời xanh ngắt phía trên đầu!",
  "Những cái bắt tay siết chặt của những người đàn ông thép giữa chảo lửa tốc độ!",
  "Màn biểu diễn khiến cho cả những vị giám khảo khó tính nhất cũng phải gật gù khen ngợi!",
  "Tất cả mọi người đều đồng ý rằng họ vừa được chứng kiến một kỳ quan của thế giới tốc độ!",
  "Một ngày hội thực sự của những trái tim đam mê tốc độ và khát khao chiến thắng!",
  "Khán giả ôm nhau nhảy múa dù chẳng hề quen biết nhau từ trước!",
  "Và tiếng reo hò đó sẽ còn vang vọng mãi trong không gian lịch sử của trường đua này!"
];

// 8. MA TRẬN CÂU CHỐT HẠ & VIRAL PUNCHLINES (100 OUTROS)
export const MASSIVE_OUTROS: string[] = [
  "Quá đẳng cấp, thực sự không còn từ ngữ nào để miêu tả nổi sự hoàn hảo này!",
  "Siuuu vang vọng từ mặt đất lên đến tận chín tầng mây xanh!",
  "Xứng đáng điểm mười không có nhưng, ban giám khảo phải gật gù bái phục!",
  "Đúng là gừng càng già càng cay, quái kiệt làng tốc độ tái xuất giang hồ!",
  "Đẳng cấp là mãi mãi, phong độ là nhất thời, đối thủ chỉ biết ngả mũ chào thua!",
  "Xem mà nổi hết cả da gà da vịt, quá đã mắt anh em ơi!",
  "Một siêu phẩm đua xe để đời của thế kỷ 21, ghi tên vào lịch sử muôn đời!",
  "Ai chê tay lái này thì bước ra đây solo ngay và luôn đi nào!",
  "Khán giả đang gào thét đến lạc cả giọng, không khí nóng hơn cả chảo lửa!",
  "Cháy hết mình trên từng cen-ti-mét đường đua, tuyệt đối đỉnh chóp!",
  "Pha xử lý mang tính biểu tượng, xem đi xem lại 100 lần vẫn thấy rùng mình!",
  "Không hổ danh là niềm tự hào của xóm đua, tài năng xuất chúng!",
  "Một tràng pháo tay giòn giã cho pha biểu diễn nghệ thuật tốc độ đỉnh cao này!",
  "Thế này thì ai mà chịu nổi nhiệt, quá tàn nhẫn với đối phương!",
  "Một khoảnh khắc ma thuật khiến triệu con tim thổn thức khôn nguôi!",
  "Cạn lời luôn rồi quý vị ơi, chỉ có thể thốt lên hai từ: Tuyệt Đỉnh!",
  "Chiến thắng ngọt ngào xóa tan mọi hoài nghi của giới mộ điệu!",
  "Chạy thế này thì đến thần gió cũng phải đứng sang một bên cúi đầu chào!",
  "Tốc độ ánh sáng cũng chỉ ngang ngửa pha bứt phá vừa rồi mà thôi!",
  "Hết nước chấm, chấm hết mọi hy vọng bám đuổi của nhóm xe phía sau!",
  "Đỉnh nóc, kịch trần, bay phấp phới giữa bầu trời rực lửa!",
  "Một pha bóng xứng đáng đi thẳng vào sách giáo khoa dạy lái xe chuyên nghiệp!",
  "Quá kinh dị, một cỗ máy chiến tranh thực thụ không có đối thủ!",
  "Ai bảo xe cỏ không chạy nhanh được thì vào đây mà xem cho mở mắt ra nhé!",
  "Đúng là phong cách của bậc đế vương, vừa chạy vừa dạo mát cũng giật cúp!",
  "Một chữ ĐỈNH kéo dài từ trường đua về tận nhà của khán giả!",
  "Đối thủ chỉ biết ôm mặt khóc ròng trong vô vọng, quá tàn nhẫn!",
  "Đây là nghệ thuật, đây là đam mê và đây là đỉnh cao của tốc độ!",
  "Màn trình diễn khiến tất cả các nhà tài trợ phải phát cuồng vì xúc động!",
  "Chiếc cúp vàng sinh ra là để dành cho đôi bàn tay tài hoa này!",
  "Không còn gì để bàn cãi, ngôi vương hôm nay đã tìm đúng chủ nhân xứng đáng!",
  "Một pha xử lý mang đẳng cấp liên hành tinh, không thuộc về trái đất này!",
  "Quá khét, khét lẹt cả trường đua lẫn trên mọi trang mạng xã hội!",
  "Hãy chia sẻ ngay khoảnh khắc lịch sử này cho 500 anh em cùng thưởng thức!",
  "Một buổi chiều ngập tràn cảm xúc thăng hoa không thể nào quên!",
  "Đúng là kẻ hủy diệt đường đua, đi đến đâu là san bằng tất cả đến đó!",
  "Xin ngả mũ bái phục trước tài năng thiên bẩm và ý chí sắt đá của anh ấy!",
  "Bản lĩnh của nhà vô địch được tôi luyện qua ngàn độ lửa thép!",
  "Cả thế giới phải nghiêng mình trước một tượng đài tốc độ bất tử!",
  "Quá đã, xem xong trận này thì tối nay mất ngủ vì quá hưng phấn!",
  "Không một ai có thể làm được điều tương tự, duy nhất và độc tôn!",
  "Một cú giáng sấm sét đập tan mọi ảo tưởng lật đổ ngai vàng!",
  "Và bây giờ, hãy tận hưởng trọn vẹn hương vị ngọt ngào của chiến thắng vinh quang!",
  "Đúng là đẳng cấp thượng thừa, không có một vết gợn nhỏ nào!",
  "Chạy xe như múa ba-lê trên mặt đường nhựa, đỉnh cao nghệ thuật!",
  "Màn trình diễn triệu đô khiến cả giải đấu phải rúng động kinh hoàng!",
  "Cảm ơn vì một siêu phẩm tốc độ đã cống hiến cho người hâm mộ khắp năm châu!",
  "Không thể tin nổi vào mắt mình, một kỳ tích vừa được tạo nên ngay trước mắt chúng ta!",
  "Chiến thắng này sẽ còn được nhắc lại trong nhiều thập kỷ tới như một huyền thoại!",
  "Quá xứng đáng, một tràng pháo tay rền vang cho người hùng của chúng ta ngày hôm nay!",
  "Đỉnh cao muôn trượng, không một đối thủ nào có thể với tới!",
  "Một màn so tài nghẹt thở xứng đáng từng xu tiền vé của người hâm mộ!",
  "Hãy đứng dậy và vỗ tay chúc mừng cho nhà vô địch vĩ đại!",
  "Tuyệt đối thuyết phục, không còn một lời bào chữa nào cho kẻ thất bại!",
  "Tốc độ, sự chuẩn xác và lòng quả cảm, tất cả hội tụ trong một con người!",
  "Một cú hích lịch sử làm rung chuyển nền tảng của môn thể thao đua xe!",
  "Đơn giản là không thể ngăn cản, như một cơn bão cấp 15 đổ bộ vào đất liền!",
  "Sức mạnh vô song đè bẹp mọi toan tính chiến thuật của đối phương!",
  "Thật vinh dự khi được trực tiếp chứng kiến khoảnh khắc huy hoàng này!",
  "Không ai có thể làm tốt hơn thế, một điểm mười tròn trĩnh cho sự hoàn hảo!",
  "Màn bứt phá xé gió xứng đáng được tạc tượng vinh danh ngay trước cổng trường đua!",
  "Một ngày thi đấu hoàn hảo ghi dấu ấn sâu đậm trong lịch sử thể thao!",
  "Những ai bỏ lỡ trận đấu hôm nay chắc chắn sẽ phải tiếc nuối cả đời!",
  "Chiến thắng giòn giã mang lại niềm tự hào vô bờ bến cho người hâm mộ!",
  "Đúng là bậc thầy tốc độ, mỗi đường cua là một nét vẽ nghệ thuật tinh tế!",
  "Không có từ ngữ nào trong từ điển đủ mạnh để miêu tả pha bóng vừa rồi!",
  "Một khoảnh khắc rực rỡ như pháo hoa thắp sáng cả bầu trời đêm!",
  "Hãy khắc ghi cái tên này vào tâm trí, bởi vì anh ấy chính là lịch sử!",
  "Sự kết hợp hoàn hảo giữa con người và cỗ máy chiến mã bất kham!",
  "Một bài học đắt giá về bản lĩnh và lòng dũng cảm cho các thế hệ tay đua trẻ!",
  "Quá xuất sắc, không còn một hạt sạn nào trong suốt toàn bộ chặng đua!",
  "Cơn mưa lời khen đang đổ dồn về phía nhà vô địch từ khắp nơi trên thế giới!",
  "Thế trận một chiều được định đoạt bởi tài năng xuất chúng của một cá nhân kiệt xuất!",
  "Một cái kết viên mãn cho một cuộc hành trình đầy chông gai và thử thách!",
  "Hào quang của chiến thắng đang soi rọi từng bước đi của anh ấy trên bục vinh quang!",
  "Quá đỉnh chóp, không có đối thủ nào đủ tầm để ngồi chung mâm hôm nay!",
  "Chiếc cúp vàng danh giá đã tìm được người chủ nhân xứng đáng nhất trên đời!",
  "Một kỷ nguyên mới của tốc độ chính thức được mở ra từ ngày hôm nay!",
  "Sự cuồng nhiệt của khán giả chính là phần thưởng xứng đáng nhất cho nỗ lực này!",
  "Và đó là tất cả những gì tinh túy nhất của môn thể thao đua xe đỉnh cao!",
  "Chiến thắng vang dội khẳng định vị thế độc tôn không thể bàn cãi!",
  "Cả cầu trường đang nghiêng ngả trước sức mạnh của cơn cuồng phong tốc độ!",
  "Một pha xử lý mang tính bước ngoặt định đoạt cả mùa giải vô địch!",
  "Tuyệt vời, kỳ diệu và không tưởng, tất cả gói gọn trong một từ: Huyền Thoại!",
  "Cảm xúc vỡ òa không thể kìm nén của những người yêu chuộng tốc độ đích thực!",
  "Một cú tạt đầu mang tính biểu tượng sẽ còn được chiếu lại hàng triệu lần trên TikTok!",
  "Đẳng cấp của một ngôi sao thực thụ luôn biết cách tỏa sáng ở thời điểm quyết định!",
  "Không còn gì nuối tiếc, một màn trình diễn chạm đến đỉnh cao của sự thăng hoa!",
  "Hãy cùng nâng ly chúc mừng cho chiến thắng vĩ đại và ngoạn mục này!",
  "Một buổi trình diễn tốc độ đỉnh cao sẽ sống mãi trong ký ức của chúng ta!",
  "Và đây chính là lý do vì sao chúng ta yêu môn thể thao đua xe đến phát cuồng!",
  "Chiến thắng của lòng dũng cảm, của đam mê cháy bỏng và của tài năng trác tuyệt!",
  "Khép lại một chặng đua ngoạn mục bằng một siêu phẩm không thể nào quên!",
  "Xin chào và hẹn gặp lại các bạn ở những chặng đua nghẹt thở tiếp theo của mùa giải!",
  "Ngôi vương tốc độ đã được định đoạt, và nó thuộc về kẻ mạnh nhất ngày hôm nay!",
  "Đỉnh nóc kịch trần, bay phấp phới muôn năm, chúc mừng nhà tân vô địch!",
  "Một ngày thi đấu đại thành công, khép lại bằng những tràng pháo tay bất tận!",
  "Vinh quang thuộc về kẻ dám dấn thân và chiến đấu đến giọt mồ hôi cuối cùng!",
  "Huyền thoại bất tử của làng đua xe thế giới, mãi mãi một niềm tự hào!",
  "Và câu chuyện huyền thoại hôm nay sẽ còn được kể lại mãi mãi về sau!"
];
