/**
 * AI Racing Commentary Vocabulary Matrix (English Edition)
 * Huge Combinatorial Vocabulary (Over 150 Quintillion Unique Combinations)
 * F1 Grand Prix Broadcast, TikTok Viral, YouTube Shorts, Electric & Hilarious Meme Style
 */

import { CommentaryCategory } from './commentaryGenerator';
import { DriverCommentaryProfile } from './commentaryVocabulary';

// ============================================================================
// 1. 100 HYPE HOOKS IN ENGLISH (MASSIVE_HOOKS_EN)
// ============================================================================
export const MASSIVE_HOOKS_EN: string[] = [
  "Earth-shattering speed rocking the entire circuit right now!",
  "At this rate, the speedometer glass is about to shatter into a million pieces!",
  "Good heavens above, did he chug five cans of rocket fuel before stepping into the cockpit?!",
  "Holy smokes ladies and gentlemen, we have absolute madness on the track!",
  "Hold onto your seats, pure mechanical fury has just been unleashed!",
  "Would you look at that sheer, unfiltered mechanical audacity!",
  "The green lights illuminate the asphalt and all hell breaks loose!",
  "Unbelievable scenes unfolding right before our very eyes!",
  "Are you kidding me right now?! That move belongs in the Hall of Fame!",
  "The entire circuit is trembling under raw, unadulterated horsepower!",
  "Smell that burning rubber and high-octane fuel cutting through the morning air!",
  "The speedometer needle just snapped clean off the dial!",
  "It simply doesn't get any more electrifying than this, folks!",
  "My heart rate is clocking 220 beats per minute right inside the commentary box!",
  "Good heavens above, a textbook maneuver executed with surgical perfection!",
  "The grandstands are on their feet screaming at the top of their lungs!",
  "A god-tier cosmic maneuver executed at supersonic Mach speed!",
  "That is downright filthy driving in the most spectacular way possible!",
  "Super Saiyan mode officially engaged, zero brakes and zero regrets!",
  "Sweet mother of speed, that near-miss took five years off my lifespan!",
  "Someone call the aerospace division, this isn't a race car, it's a supersonic jet!",
  "Total aerodynamic perfection, floating on a cushion of downforce and fury!",
  "A mind-bending slide that defied all three laws of classical Newtonian physics!",
  "Scorching hot rubber, that smelled fresher than freshly toasted bread!",
  "Warning sirens blaring across every telemetry sensor in mission control!",
  "The most insane spectacle I have witnessed in thirty years of motorsport broadcasting!",
  "An armored beast unleashed straight from the depths of automotive fury!",
  "Hold your breath everyone, one hundredth of a second dictates absolute destiny!",
  "Engine cylinder temperatures are boiling red-hot into the redline zone!",
  "Even a category-five hurricane would bow down to this blitzkrieg pace!",
  "Oh boy, an audacious dummy move that left the entire grid paralyzed with awe!",
  "The God of Speed has personally descended upon this asphalt battlefield!",
  "Dispatch the fire brigade immediately before this tarmac melts into liquid lava!",
  "Heaven help us all, what did our broadcast camera lenses just capture?!",
  "Do not blink! I repeat, do not dare blink for a single fraction of a second!",
  "Twin-turbo wastegates screaming like thunder rolling across the open sky!",
  "One merciless stomp on the throttle pedal tears spacetime wide open!",
  "Spectators are clutching their heads in utter, speechless disbelief!",
  "An earth-shattering show that deserves ten million viral shares across the globe!",
  "There is simply no containing the unleashed rage of this twin-turbocharged V12 monster!",
  "A ruthless asphalt predator that devours apexes for an afternoon snack!",
  "Millions of viewers around the globe are roaring in unison right now!",
  "Stunned, mesmerized, and paralyzed by sheer driving brilliance!",
  "Painting the turn with glowing sparks and a magnificent wall of white tire smoke!",
  "Goosebumps from head to toe, this is pure liquid adrenaline distilled!",
  "Frame that maneuver and hang it in the world museum of automotive greatness!",
  "Supersonic aerodynamic roar cutting straight through the atmospheric envelope!",
  "A magnitude-nine earthquake just shook the core of this raceway!",
  "A blur of neon aerodynamic fury streaking past our high-speed lenses!",
  "Hats off to a racing prodigy born to shatter physical limitations!",
  "Lord have mercy, driving with this level of ferocity is simply unfair to mortal opponents!",
  "Explosive drama, the greatest rivalry of the modern era erupts into full combat!",
  "Microscopic clearance, squeezing through a gap narrower than a credit card!",
  "Pistons hammering at fourteen thousand RPM like a heavy metal percussion solo!",
  "Hypnotized and captivated by the symphony of peak mechanical engineering!",
  "A golden lap that will be studied in racing academies for generations to come!",
  "The apex was clipped with the surgical precision of a military-grade laser beam!",
  "Absolute savagery on four forged magnesium wheels!",
  "No fear, no hesitation, pure instinctive genius behind the wheel!",
  "The turbo whistle is loud enough to shatter plate glass across three zip codes!",
  "Defying gravity, inertia, and common sense in a single breath!",
  "Look at the telemetry trace, the throttle hasn't lifted for three straight sectors!",
  "An adrenaline tsunami is sweeping over the entire racing paddock!",
  "A masterclass in controlled chaos at 300 miles per hour!",
  "Rubber laid down with artistic perfection, what a magnificent masterpiece!",
  "The atmosphere is electric, the tension is thick enough to cut with a diamond blade!",
  "Incredible reflex recovery from what looked like a fatal tank-slapper!",
  "Blink and you miss history being rewritten right in front of you!",
  "The chase car's headlights are vibrating under brutal aerodynamic turbulence!",
  "A fearless charge straight into the belly of the beast!",
  "Pure mechanical euphoria resonating through the grandstand concrete!",
  "The roar of the exhaust pipe sounds like an angry dragon waking from hibernation!",
  "Precision cornering that would make a fighter jet pilot weep with joy!",
  "A daredevil maneuver executed with pure liquid nitrogen in the veins!",
  "Hold the phone, we have an absolute barnburner of a contest on our hands!",
  "Every single horse under that carbon-fiber hood is galloping at maximum fury!",
  "A lightning bolt wrapped in hand-laid autoclave carbon fiber!",
  "Nothing short of theatrical drama on high-octane steroids!",
  "The track marshals are applauding on the service road, and who can blame them?!",
  "Downshifting with savage rev-matched pops that rattle your teeth!",
  "An all-or-nothing blitzkrieg charge down the main front stretch!",
  "The rival car has to check its mirrors because a guided missile is incoming!",
  "Audacious, ruthless, and absolutely breathtaking in every conceivable metric!",
  "Screaming down into turn one like a meteor re-entering the atmosphere!",
  "You cannot teach this kind of raw, unfiltered competitive instinct!",
  "The slipstream draft is acting like a sonic tractor beam right now!",
  "Fender-to-fender, mirror-to-mirror, this is gladiatorial combat on wheels!",
  "Heart in mouth, breath in chest, that was millimeter-perfect execution!",
  "The apex was clipped so hard the curb is practically filing a police report!",
  "Absolute cinematic perfection delivered at triple-digit speeds!",
  "A battle of wits, horsepower, and nerves of reinforced titanium!",
  "Look at the downforce flexing the rear wing endplates to the absolute brink!",
  "Spectators are climbing the safety fence just to catch a glimpse of this showdown!",
  "A relentless assault on the race lead that will go down in racing folklore!",
  "The brake calipers are glowing molten orange through the wheel spokes!",
  "Tires squealing in agony as five tons of aerodynamic load crush them into the tarmac!",
  "An offensive blitz that caught the championship leader completely off-guard!",
  "Unapologetic speed, unmatched composure, and undeniable swagger!",
  "The commentator's headset is practically shaking from the shockwave!",
  "Ladies and gentlemen, this is what championship-caliber racing looks like!",
  "Clear the runway, because a rocket ship just arrived on the racing grid!"
];

// ============================================================================
// 2. 50 TRACK ENVIRONMENTS IN ENGLISH (TRACK_ENVIRONMENTS_EN)
// ============================================================================
export const TRACK_ENVIRONMENTS_EN: string[] = [
  "on the scorching Monza highway with smoking asphalt under the blazing sun",
  "screaming through the mountain tunnel with thunderous exhaust resonance",
  "threading through the ninety-degree death hairpin with millimeters to spare",
  "slipping and sliding across rain-drenched tarmac slick as greased glass",
  "battling fierce crosswinds across the ocean suspension bridge",
  "conquering the twenty-two-degree banking of the high-speed oval",
  "slicing through the cyberpunk neon skyline in the dead of midnight",
  "skimming past the Mediterranean marina where superyachts rock in the wake",
  "powersliding through the red desert canyon under a fiery dust storm",
  "attacking the alpine mountain pass surrounded by snow-covered peaks",
  "streaking past the neon-drenched skyscrapers of the downtown sector",
  "roaring across the ocean coastal suspension bridge at Mach 1",
  "carving through the treacherous mountain hairpin apex with sheer cliff drops",
  "navigating the blinding cyberpunk rainy straight under dazzling halogen lights",
  "flying over the roller-coaster crest of the high-speed forest circuit",
  "blasting through the underground transit tunnel with deafening exhaust resonance",
  "drifting along the sun-baked desert canyon chicane surrounded by red dust storms",
  "negotiating the narrow historic cobblestone streets of the European grand prix",
  "rocketing down the endless three-kilometer runway straightaway",
  "powering through the corkscrew chicane under the fiery twilight sky",
  "conquering the triple-apex parabolic banking with maximum positive G-forces",
  "slicing through dense foggy mountain passes with headlights slicing the mist",
  "skimming past the glittering seaside marina filled with luxury superyachts",
  "attacking the steep eighteen-percent incline grade with smoking tires",
  "shooting through the hyper-modern futuristic airport terminal raceway",
  "powersliding through the rain-slicked asphalt labyrinth with rooster tails of spray",
  "charging into the technical chicane under the scorching midday sun",
  "threading the needle through the tight warehouse dockyard container alley",
  "diving into the subterranean mega-structure bypass loop",
  "flying past the packed grandstands on the iconic start-finish front straight",
  "blasting through the illuminated neon cyber-oasis in the dead of night",
  "tackling the unforgiving S-curves with razor-sharp carbon curbs",
  "roaring through the alpine snow-capped valley with crisp freezing air",
  "skimming across the glass-smooth newly resurfaced asphalt ribbon",
  "charging through the industrial refinery corridor under towering flare stacks",
  "slicing across the elevated highway interchange with dizzying drops below",
  "cutting through the scenic hillside vineyard sweeps at full throttle",
  "blitzing through the grand casino boulevard lined with cheering VIP crowds",
  "drifting around the harbor sea-wall perimeter with ocean waves crashing alongside",
  "blasting down the high-speed banking with seventy-degree tilt angles",
  "screaming past the pit wall where mechanics are hanging over the barrier",
  "carving through the shadowy ancient temple ruins backdrop at dusk",
  "rocketing through the illuminated stadium super-dome under blinding floodlights",
  "negotiating the ultra-fast downhill chicane with suspension bottoming out",
  "threading through the tight downtown subway overpass chicanes",
  "barreling through the dusty savannah cross-country sector",
  "slicing through the emerald green rainforest canopy highway",
  "flying down the scenic lakeside ribbon with sunset reflection on the windshield",
  "navigating the multi-level parking mega-complex rooftop interchange",
  "powering across the roaring international expressway loop"
];

// ============================================================================
// 3. 60 TACTICAL FLAVORS IN ENGLISH (TACTICAL_FLAVORS_EN)
// ============================================================================
export const TACTICAL_FLAVORS_EN: string[] = [
  "with heel-and-toe clutch wizardry that borders on martial arts mastery",
  "with a bone-chilling late-braking dive just inches before the fatal barrier",
  "with neural synaptic reflexes faster than an electrical impulse",
  "with sheer cold-blooded ruthlessness and nerves of forged steel",
  "feathering the throttle with microscopic millimeter precision",
  "executing a flawless Scandinavian flick to swing the rear end around",
  "riding the serrated red-and-white curbs to slingshot with maximum momentum",
  "cutting off the racing line with aggressive champion body-language",
  "trail-braking all the way to the geometric center of the apex",
  "short-shifting under high lateral Gs to maintain tire traction",
  "feinting left before snap-countersteering straight into the slipstream vacuum",
  "dropping two gears and dumping raw twin-turbo boost into the rear differential",
  "late-braking at the absolute 50-meter board with burning carbon-ceramic rotors",
  "activating ultrasonic DRS flap angle with flawless aerodynamic trim",
  "utilizing a Scandinavian flick to pitch the chassis into a four-wheel drift",
  "hugging the inner apex line so tightly that not even a sheet of paper could slip through",
  "unleashing the computerized anti-lag system with explosive backfires",
  "switching to maximum attack mode on engine map eight",
  "executing a classic switchback undercut out of the slow hairpin",
  "timing the draft to perfection before pulling out with a hydraulic boost surge",
  "locking the front differential to claw maximum mechanical grip from the tarmac",
  "deploying kinetic energy recovery power with an electric torque kick",
  "running a daring high-line arc to carry fifty kilometers of extra entry speed",
  "forcing the rival onto the dirty marbles on the outside apron",
  "setting up the dive-bomb with calculated cold-blooded ruthlessness",
  "balancing the chassis on the absolute knife-edge of lateral tire friction",
  "flicking the steering wheel with the dexterity of a concert pianist",
  "applying threshold braking right on the verge of ABS pulse lockup",
  "pre-rotating the front axle before clipping the inside sausage curb",
  "feathering the hydraulic handbrake lever to tuck the nose inward",
  "unwinding the steering lock smoothly to maximize exit traction",
  "snapping the paddle shifter with explosive pneumatic precision",
  "harnessing the low-pressure eddy currents behind the lead diffuser",
  "diving into the dirty air pocket with supreme downforce confidence",
  "reading the track temperature shifts with veteran tactical instinct",
  "countering a snap oversteer twitch with instantaneous opposite lock",
  "setting a defensive diamond line to protect the inside braking zone",
  "milking every ounce of momentum out of the negative camber turn",
  "snatching the racing line like a hawk swooping on its prey",
  "dumping kinetic recovery boost on corner exit to break the tow",
  "bluffing to the outside before darting into the wide-open inside gap",
  "riding the throttle pedal right at the edge of wheelspin threshold",
  "inducing mild lift-off oversteer to rotate through the tight chicane",
  "scrubbing front tire scrub angle to generate instantaneous bite",
  "pinning the accelerator to the firewall without a microsecond of doubt",
  "dancing across the wet white line without losing a degree of yaw",
  "using the curb elevation change to unweight the inner suspension",
  "clamping down the carbon rotors with four hundred pounds of leg pressure",
  "timing the upshift crackle right at twelve thousand RPM redline",
  "snapping into the slipstream pocket like a supersonic docking clamp",
  "baiting the opponent into braking five meters too early",
  "hugging the concrete retaining wall with two millimeters of clearance",
  "flicking through the S-bends with zero steering deadband delay",
  "unleashing three hundred bars of direct fuel injection pressure",
  "balancing front and rear aero balance with active cockpit trim dials",
  "charging the apex like a guided laser-targeted projectile",
  "riding the aerodynamic wash with seasoned open-wheel bravado",
  "finessing the steering angle to prevent front-tire graining",
  "delivering an absolute clinic in defensive positional placement",
  "sealing the exit corner speed with mathematical geometrical perfection"
];

// ============================================================================
// 4. 35 EXTENDED DRIVER PROFILES IN ENGLISH (EXTENDED_DRIVER_PROFILES_EN)
// ============================================================================
export const EXTENDED_DRIVER_PROFILES_EN: Record<string, DriverCommentaryProfile> = {
  'Cristiano Ronaldo': {
    name: 'Cristiano Ronaldo',
    aliases: ['CR7', 'The Portuguese Phenom Cristiano Ronaldo', 'The Apex Predator CR7', 'El Comandante Ronaldo', 'Cristiano Ronaldo'],
    signatureGag: 'hitting the apex with the precision of a knuckleball free-kick',
    shoutout: 'SIUUU! The five-time Ballon d\'Or champion claims supreme dominion over the raceway!'
  },
  'Lionel Messi': {
    name: 'Lionel Messi',
    aliases: ['The Maestro Lionel Messi', 'El Pulga Messi', 'The World Champion Lionel Messi', 'The Magician Messi', 'Lionel Messi'],
    signatureGag: 'gliding through the chicane with mesmerizing slalom balance',
    shoutout: 'Pure genius from Rosario! The Greatest of All Time paints an artistic masterpiece on wheels!'
  },
  'Kylian Mbappe': {
    name: 'Kylian Mbappe',
    aliases: ['The Supersonic Frenchman Kylian Mbappe', 'Ninja Turtle Mbappe', 'The Turbo Wonderkid Mbappe', 'Donatello Mbappe', 'Kylian Mbappe'],
    signatureGag: 'blitzing the back straightaway with Olympic sprint velocity',
    shoutout: 'Unstoppable Parisian lightning! The young king burns the asphalt to a crisp!'
  },
  'Erling Haaland': {
    name: 'Erling Haaland',
    aliases: ['The Nordic Cyborg Erling Haaland', 'The Goal Machine Haaland', 'The Viking Juggernaut Haaland', 'Berserker Haaland', 'Erling Haaland'],
    signatureGag: 'smashing through the chicane with unstoppable brute mechanical force',
    shoutout: 'Cyborg mode activated! The Norwegian powerhouse crushes all opposition in his path!'
  },
  'David Beckham': {
    name: 'David Beckham',
    aliases: ['The Free-Kick Maestro Beckham', 'Golden Balls Beckham', 'Sir David Beckham', 'The Curve Master Beckham'],
    signatureGag: 'bending the trajectory around the apex with sublime curving accuracy',
    shoutout: 'Bend it like Beckham! Pure English football royalty takes over the racing circuit!'
  },
  'Neymar Jr': {
    name: 'Neymar Jr',
    aliases: ['The Samba Drift King Neymar Jr', 'The Prince of Joga Bonito Neymar', 'The Brazilian Showman Neymar Jr', 'Neymar Jr'],
    signatureGag: 'dancing through the hairpins with intoxicating samba rhythm',
    shoutout: 'Carnival in full bloom! Neymar serves up pure Brazilian motorsport magic!'
  },
  'Ronaldinho': {
    name: 'Ronaldinho',
    aliases: ['The Magician Ronaldinho Gaucho', 'The Smile of Football Ronaldinho', 'Dinho', 'Ronaldinho'],
    signatureGag: 'throwing an elastico feint on four wheels that leaves rivals confused',
    shoutout: 'Oley! Ronaldinho brings pure joy, magic, and samba swagger to the racetrack!'
  },
  'Ronaldo Nazario': {
    name: 'Ronaldo Nazario',
    aliases: ['R9 O Fenômeno', 'El Fenomeno Ronaldo', 'The Original Ronaldo', 'R9'],
    signatureGag: 'exploding past defenders with uncontrollable explosive pace and stepovers',
    shoutout: 'The Fenomeno has arrived! Pure unstoppable Brazilian greatness on wheels!'
  },
  'Zlatan Ibrahimovic': {
    name: 'Zlatan Ibrahimovic',
    aliases: ['Lord Zlatan', 'The Lion Ibrahimovic', 'God of Milan Zlatan', 'Zlatan Ibrahimovic'],
    signatureGag: 'taekwondo-kicking the brake pedal with supreme lion-hearted confidence',
    shoutout: 'Lions do not compare themselves to humans! Zlatan does not race cars, cars race for Zlatan!'
  },
  'Zinedine Zidane': {
    name: 'Zinedine Zidane',
    aliases: ['Zizou', 'The Roulette Maestro Zidane', 'French Royalty Zidane', 'Zinedine Zidane'],
    signatureGag: 'spinning through the chicane with a silky Marseille roulette motion',
    shoutout: 'Magnifique! Zizou orchestrates the raceway with pure French elegance and tactical genius!'
  },
  'Diego Maradona': {
    name: 'Diego Maradona',
    aliases: ['D10S Maradona', 'The Golden Boy of Napoli Maradona', 'El Pibe de Oro', 'Diego Maradona'],
    signatureGag: 'dribbling past five cars in a row with cosmic Argentine flair',
    shoutout: 'The Hand of God strikes again! Cosmic genius on the asphalt ribbon!'
  },
  'Thierry Henry': {
    name: 'Thierry Henry',
    aliases: ['King Henry', 'The Highbury Magician Henry', 'Titi Henry', 'Thierry Henry'],
    signatureGag: 'opening up his body and slotting the car into the bottom-corner apex',
    shoutout: 'Va-va-voom! King Henry delivers pure Gallic swagger and untouchable finesse!'
  },
  'Max Verstappen': {
    name: 'Max Verstappen',
    aliases: ['Super Max', 'The Flying Dutchman Verstappen', 'Mad Max', 'Max Verstappen'],
    signatureGag: 'dive-bombing the inside line with zero remorse and zero lifting',
    shoutout: 'Simply lovely! Super Max establishes ruthless Dutch dominance once again!'
  },
  'Lewis Hamilton': {
    name: 'Lewis Hamilton',
    aliases: ['LH44', 'Sir Lewis Hamilton', 'The Seven-Time Champion Hamilton', 'Lewis Hamilton'],
    signatureGag: 'channeling hammer-time pace with tire-whispering masterclass precision',
    shoutout: 'It\'s Hammer Time! Still I Rise! Lewis Hamilton demonstrates championship immortality!'
  },
  'Charles Leclerc': {
    name: 'Charles Leclerc',
    aliases: ['Lord Perceval', 'Il Predestinato Leclerc', 'The Prince of Monaco Leclerc', 'Charles Leclerc'],
    signatureGag: 'putting it on pole with sensational qualifying commitment over the curbs',
    shoutout: 'Il Predestinato! The Monegasque maestro sends Tifosi hearts racing into orbit!'
  },
  'Lando Norris': {
    name: 'Lando Norris',
    aliases: ['The Twitch Prodigy Lando Norris', 'Papaya Rocket Norris', 'Lando Nowins Norris', 'Lando Norris'],
    signatureGag: 'flipping on Scenario Seven boost with lightning-fast streaming banter',
    shoutout: 'Scenario Seven engaged! Lando Norris lights up the leaderboard in brilliant papaya!'
  },
  'Fernando Alonso': {
    name: 'Fernando Alonso',
    aliases: ['El Nano', 'Samurai Alonso', 'The Asturian Gladiator Alonso', 'Fernando Alonso'],
    signatureGag: 'wrestling the chassis with two decades of veteran cunning and grit',
    shoutout: 'Trust the plan! The eternal Samurai proves age is just a number on the speedometer!'
  },
  'Son Tung M-TP': {
    name: 'Son Tung M-TP',
    aliases: ['Sky Chairman Son Tung M-TP', 'Prince of V-Pop Son Tung', 'Boss Tung', 'Son Tung M-TP'],
    signatureGag: 'dropping the clutch while humming an unstoppable chart-topping anthem',
    shoutout: 'We belong together! Chairman Son Tung leads the entire Sky empire across the finish line!'
  },
  'Do Mixi': {
    name: 'Do Mixi',
    aliases: ['Tribal Chief of Cao Bang Do Mixi', 'MixiGaming', 'Toc Truong Do Mixi', 'Do Mixi'],
    signatureGag: 'slamming the steering wheel with authentic Cao Bang clan enthusiasm',
    shoutout: 'From Cao Bang to the global podium! The Tribal Chief claims victory for the entire tribe!'
  },
  'Faker': {
    name: 'Faker',
    aliases: ['The Unkillable Demon King Faker', 'Hall of Legends Faker', 'Lee Sang-hyeok', 'Faker'],
    signatureGag: 'dodging incoming dive-bombs with superhuman micro-movement APM',
    shoutout: 'All roads lead to him! The Unkillable Demon King claims another world championship!'
  },
  'IShowSpeed': {
    name: 'IShowSpeed',
    aliases: ['Speedy', 'The Barking Sensation IShowSpeed', 'Darren Watkins Jr', 'IShowSpeed'],
    signatureGag: 'howling at the windshield while attempting a 360-degree backflip burnout',
    shoutout: 'SUIII! SEWER! IShowSpeed brings absolute unhinged internet energy to the racetrack!'
  },
  'PewDiePie': {
    name: 'PewDiePie',
    aliases: ['The Bro Army General PewDiePie', 'Felix Kjellberg', 'Meme Review King', 'PewDiePie'],
    signatureGag: 'delivering a brofist to the dashboard while holding top speed on the rev-limiter',
    shoutout: 'Floor Gang victory! PewDiePie rallies the hundred-million-strong Bro Army!'
  },
  'MrBeast': {
    name: 'MrBeast',
    aliases: ['Jimmy Donaldson MrBeast', 'The Hundred-Million Dollar Philanthropist', 'Feastables King', 'MrBeast'],
    signatureGag: 'giving away a gold-plated hypercar to whoever survives the turn-one pileup',
    shoutout: 'I just bought this entire raceway! MrBeast pulls off the biggest stunt in motorsport history!'
  },
  'Khaby Lame': {
    name: 'Khaby Lame',
    aliases: ['The Silent Master Khaby Lame', 'Life Hack Smasher Khaby', 'The Shrug King', 'Khaby Lame'],
    signatureGag: 'shrugging casually with both palms extended while overtaking with one hand',
    shoutout: 'Zero words needed! Khaby Lame demonstrates that going fast was simply this easy!'
  },
  'Soobin Hoang Son': {
    name: 'Soobin Hoang Son',
    aliases: ['Prince of R&B Soobin', 'Dancing Ace Soobin Hoang Son', 'Playboy Soobin', 'Soobin Hoang Son'],
    signatureGag: 'sliding through the chicane with smooth choreography and flawless rhythm',
    shoutout: 'Pure stage presence! Soobin turns the racetrack into an electrifying R&B concert!'
  },
  'Dominic Toretto': {
    name: 'Dominic Toretto',
    aliases: ['Dom Toretto', 'Vin Diesel', 'The Man Who Rides For Family', 'Dominic Toretto'],
    signatureGag: 'double-clutching like you should while whispering about the importance of family',
    shoutout: 'I don\'t have friends, I got family! Dom Toretto crosses the line on two wheels with quarter-mile fury!'
  },
  'Takumi Fujiwara': {
    name: 'Takumi Fujiwara',
    aliases: ['Akina Downhill Legend Takumi', 'Ghost of the AE86 Fujiwara', 'Tofu Delivery King', 'Takumi Fujiwara'],
    signatureGag: 'sliding the gutter run without spilling a single drop of water from the paper cup',
    shoutout: 'Eurobeat intensifies! The Akina downhill ghost delivers tofu and a legendary victory!'
  },
  'Lightning McQueen': {
    name: 'Lightning McQueen',
    aliases: ['Number 95 Lightning McQueen', 'Rust-eze Champion McQueen', 'Piston Cup Legend', 'Lightning McQueen'],
    signatureGag: 'sticking the tongue out while executing a high-speed dirt-track countersteer',
    shoutout: 'Kachow! Speed, I am speed! Lightning McQueen captures another historic Piston Cup triumph!'
  },
  'Ghost Rider': {
    name: 'Ghost Rider',
    aliases: ['The Flaming Hellfire Stuntman', 'Spirit of Vengeance', 'Johnny Blaze', 'Ghost Rider'],
    signatureGag: 'igniting the asphalt into glowing red brimstone as the rear tires spin',
    shoutout: 'Look into my eyes! The Spirit of Vengeance leaves a trail of pure hellfire across the tarmac!'
  },
  'Shadow Boss': {
    name: 'Shadow Boss',
    aliases: ['The Anonymous Phantom', 'Blackout Drifter', 'The Silent Menace', 'Shadow Boss'],
    signatureGag: 'vanishing into the smoke and reappearing in first position out of thin air',
    shoutout: 'The mysterious shadow reigns supreme! An anonymous icon vanquishes the entire grid!'
  },
  'Kevin De Bruyne': {
    name: 'Kevin De Bruyne',
    aliases: ['The Master Tactician Kevin De Bruyne', 'KDB', 'The Belgian Visionary De Bruyne', 'Kevin De Bruyne'],
    signatureGag: 'calculating the racing line down to the exact millimeter angle',
    shoutout: 'Surgical Belgian perfection! KDB threads the needle like a GPS-guided missile!'
  },
  'Luka Modric': {
    name: 'Luka Modric',
    aliases: ['The Maestro of Zadar Luka Modric', 'Golden Trivela King Modric', 'The Balkan Magician', 'Luka Modric'],
    signatureGag: 'carving the outside of the corner with exquisite trivela-like steering curvature',
    shoutout: 'Pure class, timeless magic! Luka Modric conducts the mechanical orchestra with gold-medal poise!'
  },
  'Jude Bellingham': {
    name: 'Jude Bellingham',
    aliases: ['Belligol Jude Bellingham', 'The Golden Boy Bellingham', 'The Midfield General Jude Bellingham', 'Jude Bellingham'],
    signatureGag: 'dominating the mid-corner apex with royal elegance and power',
    shoutout: 'Hey Jude! Arms outstretched in glory as Bellingham takes the checkered flag!'
  },
  'Vinicius Jr': {
    name: 'Vinicius Jr',
    aliases: ['Vini Jr', 'The Brazilian Electric Wire Vinicius Jr', 'The Speed Sensation Vini Jr', 'Vinicius Jr'],
    signatureGag: 'blistering down the flank with dazzling stepover countersteering',
    shoutout: 'Electric flair! Vini Jr dances past defenders with unstoppable pace and flair!'
  },
  'Harry Kane': {
    name: 'Harry Kane',
    aliases: ['Hurricane Kane', 'The Golden Striker of London', 'Captain Kane', 'Harry Kane'],
    signatureGag: 'striking the apex with thunderous clinical accuracy that finds the top corner',
    shoutout: 'Hurricane warning in full effect! Harry Kane smashes the record books wide open!'
  }
};

// ============================================================================
// 5. 320+ DETAILED ACTIONS ACROSS 10 SITUATIONS (MASSIVE_ACTIONS_EN)
// ============================================================================
export const MASSIVE_ACTIONS_EN: Record<CommentaryCategory, string[]> = {
  START: [
    "dumped the clutch and launched like an intercontinental ballistic missile",
    "hooked up all four slick tires instantly with zero wheelspin off the line",
    "fired out of the starting blocks like an angry lightning bolt",
    "ignited the twin turbochargers and rocketed past three rows of rivals",
    "pulled a flawless launch-control start with perfect tachometer rev-hold",
    "blitzed off the grid leaving two blackened rubber strips burned into the tarmac",
    "sliced through the front pack with predatory reaction time of 0.08 seconds",
    "lunged into the first corner taking the commanding inside line",
    "nailed the reaction lights before anyone else could blink an eyelid",
    "catapulted forward under four-wheel drive torque, instantly grabbing the hole shot",
    "rocketed from dead stop to two hundred kilometers an hour in two heartbeats",
    "unleashed full antilag boost right as the starting gantry extinguished",
    "gained four positions before even reaching third gear",
    "executed a textbook drag-racing launch with zero axle tramp",
    "sliced through the opening chicane melee with nerves of ice",
    "jumped the start right on the legal ragged edge with millimeter precision",
    "pinned the accelerator pedal to the floorboards leaving a haze of blue tire smoke",
    "blasted through the midfield pack like an armor-piercing round",
    "surged past the front row before the competitors could even engage second gear",
    "locked down the preferred racing line into turn one with total authority",
    "launched with such violent acceleration that the front splitter grazed the curbs",
    "showcased reflexes honed in flight simulators to steal the race lead",
    "squeezed between two stalled cars on the grid with microscopic clearance",
    "turned horsepower into instant lateral momentum on the opening straight",
    "pulled five Gs of launch acceleration off the starting line grid box",
    "ignited the crowd with an explosive departure off the start-finish straight",
    "slingshotted around the outside row of rivals with fearless commitment",
    "carved out an immediate two-car-length cushion entering the first braking zone",
    "unloaded twelve hundred horsepower straight into the asphalt",
    "timed the clutch release to the exact millisecond of the green light flash",
    "swept into turn one with the grace of a fighter jet taking off from an aircraft carrier",
    "stormed into the lead pack with a ferocious declaration of championship intent"
  ],
  NITRO: [
    "punched the dual-stage nitrous oxide purge button and entered warp speed",
    "dumped liquid nitro into the intake manifold, spewing two-meter blue exhaust flames",
    "activated emergency hyper-boost, lifting the front splitter off the pavement",
    "unleashed two thousand horsepower of raw compressed nitrous fury",
    "fired the twin bottle purge and transformed into an unrecognizable silver missile",
    "hit the nitrous valve and rocketed past the speed trap at orbital velocity",
    "unleashed liquid nitrous oxide, turning the exhaust tips into roaring jet afterburners",
    "spat blinding violet flames from the titanium pipes as the boost spiked",
    "surged forward with instant nitrous torque that shoved the chassis into the asphalt",
    "deployed emergency overtake boost, disintegrating the gap in half a second",
    "injected pure chemical horsepower, shattering the local sound barrier",
    "dumped the secondary nitrous reservoir, creating an incandescent tail of fire",
    "unleashed a deafening supersonic roar as the twin bottles reached maximum flow",
    "catapulted down the straightaway like a guided cruise missile on afterburner",
    "blitzed the speed radar gun, causing the sensor display to overload",
    "ignited the hyper-nitro injectors, turning the rear wing into an aerodynamic vapor cone",
    "unleashed a furious blast of pressurized gas that practically sucked the air out of the tunnel",
    "surged with unholy acceleration, blowing past the rival before they could react",
    "fired the liquid power shot, leaving glowing carbon residue along the straightaway",
    "unlocked stage-three nitrous mapping, generating enough thrust to launch an aircraft",
    "activated hyper-propulsion mode, screaming down the tarmac at Mach 1.2",
    "dumped the full bottle in one heroic burst, leaving trailing shockwaves in the air",
    "spewed two-foot flames on the downshift before unleashing full chemical fury",
    "boosted past the speed limit sign with comical, law-defying speed",
    "turned the asphalt into an aircraft runway with continuous nitrous injection",
    "flooded the cylinders with cryogenic power, screaming past five hundred kilometers per hour",
    "discharged the emergency kinetic boost, creating a blinding flash in the rear mirrors",
    "punched through the wall of wind resistance with pure rocket-assisted momentum",
    "blasted down the straight with twin exhaust plumes lighting up the twilight",
    "dumped the ultimate reserve boost, stretching the straightaway lead to fifty meters",
    "cracked open the nitrous regulator, producing a sonic boom that echoed for miles",
    "unleashed raw chemical rage that pinned the driver back into the carbon bucket seat"
  ],
  DRIFT: [
    "yanked the hydraulic handbrake and pitched the car into a continuous 90-degree smoky slide",
    "held an unbelievable four-wheel drift along the retaining wall with three millimeters to spare",
    "counter-steered through the hairpin producing a majestic tsunami of tire smoke",
    "danced the rear axle around the curbing with the finesse of a prima ballerina",
    "maintained an insane angle of attack without scrubbing off a single kilometer of speed",
    "carved a sideways donut arc that drew a standing ovation from the corner marshals",
    "flicked the chassis into full reverse-entry drift, blinding the chase pack with rubber smoke",
    "kissed the outside clipping point with the rear bumper diffuser at 180 km/h",
    "slid through the double-apex carousel with steering wheel locked in opposite direction",
    "maintained a jaw-dropping sixty-degree drift angle while feathering the clutch",
    "painted the tarmac with two thick parallel ribbons of smoldering molten rubber",
    "swept through the transition with razor-sharp balance, linking both hairpins seamlessly",
    "unleashed a smokescreen so dense the trailing cars had to navigate by radar",
    "skimmed the concrete barrier with the rear wing endplate without peeling the paint",
    "rotated the car around its vertical axis with telepathic throttle modulation",
    "powerslidded through the downhill chicane with all four wheels smoking in unison",
    "held an absurd drift angle across seventy meters of high-speed parabolic curve",
    "counter-steered with microscopic thumb adjustments to balance on the knife edge",
    "scraped the rear curb while keeping the front wheels pointed directly at the apex",
    "threw the vehicle into an inertia slide that defied every law of tire mechanics",
    "executed a flawless wall-tap drift that set off the proximity sensors in the barrier",
    "danced across the painted curbs with theatrical flair and precision",
    "swept sideways through turn three at speeds that would make rally legends blush",
    "feathered the gas pedal in third gear, smoking the rear tires down to the canvas",
    "snapped from left-drift to right-drift with instantaneous hydraulic responsiveness",
    "floated through the hairpin like an automotive hovercraft riding on white smoke",
    "balanced lateral G-forces with supernatural poise while looking through the side window",
    "drifted past the grandstands drawing a thunderous roar from fifty thousand fans",
    "slid past the apex marker cone with centimeters of clearance and zero speed loss",
    "carved a continuous figure-eight drift loop that will dominate social media for weeks",
    "whipped the tail out in full view of the broadcast chopper, pure cinematic poetry",
    "rode the edge of adhesion with artistic drift mastery that redefined vehicle dynamics"
  ],
  OVERTAKE: [
    "lunged down the inside with an audacious late-braking maneuver that stunned everyone",
    "executed an exquisite switchback crossover, taking the lead on corner exit",
    "swept around the outside sweeping arc carrying mind-blowing aerodynamic momentum",
    "dove into the hairpin apex, snatching the race lead with surgical precision",
    "capitalized on a microscopic mistake and swept past without leaving an inch of room",
    "swapped paint in a thrilling wheel-to-wheel scuffle before pulling away ahead",
    "snatched the lead cleanly through the slipstream draft, dropping the hammer",
    "braked twenty meters later than humanly possible to steal the inside line",
    "bluffed to the right before ducking back to the left in a sensational dummy move",
    "slingshotted out of the slipstream tow, roaring past before the braking zone",
    "dove down the inside of turn one, clamping the brakes and slamming the door shut",
    "muscled through on the outside apron with two wheels kicking up roadside gravel",
    "split two slower backmarkers down the center in a heart-stopping three-wide pass",
    "exploited a half-meter opening on the kerb, squeezing past with predatory instinct",
    "pulled off an impossible round-the-outside maneuver at two hundred miles an hour",
    "timed the DRS opening to perfection, sailing past the defending champion like a phantom",
    "punished a wide corner entry, carving underneath to claim the race lead",
    "rode the slipstream wave down the main straight, pulling ahead at the line",
    "executed an audacious dive-bomb that forced the rival to yield track position",
    "threaded the needle between the pit wall and the rival car with razor clearance",
    "claimed the apex by pure right of mechanical bravery and superior braking power",
    "slid past on the inside while maintaining full opposite-lock car control",
    "snatched P1 with an uncompromising pass that left the entire pit crew speechless",
    "made a breathtaking wheel-to-wheel pass through the fastest chicane on the circuit",
    "snapped out of the rival's tow and completed the pass before reaching the apex",
    "out-accelerated the competition on corner exit with superior differential hookup",
    "sliced through the defending car's defensive block with surgical millimeter precision",
    "swept around the high line with supreme confidence in front-end aerodynamic grip",
    "slung past on the downhill section, taking the lead with jaw-dropping bravado",
    "delivered a clinical overtaking lesson that will be replayed on sports reels forever",
    "dove into the narrowest gap imaginable and emerged in the lead unscathed",
    "swapped positions on the ragged edge, sealing the pass with a crisp throttle snap",
    "snatched victory from the jaws of defeat with a last-lap overtaking masterpiece",
    "stormed past with such sheer velocity that the rival car visibly rocked in the wake",
    "completed an unforgettable pass that brought the entire commentary booth to its feet"
  ],
  BATTLE: [
    "locked into a heart-stopping side-by-side duel with wheel rims scraping together",
    "trading paint and aggressive track position with neither driver willing to yield an inch",
    "sparring through three consecutive corners with millimeters separating carbon bodywork",
    "engaged in a ferocious psychological chess match at 200 miles per hour",
    "swapping positions back and forth like a high-octane pendulum of mechanical warfare",
    "running wheel-to-wheel down the straightaway with open throttles and clenched fists",
    "rubbing carbon-fiber door mirrors at triple-digit speeds through the sweeping turn",
    "locked in gladiatorial combat where one single twitch could mean disaster for both",
    "trading apexes corner after corner in an epic clash of generational driving titans",
    "banging wheels down the front straight, neither competitor backing off for a second",
    "shadowing each other's bumper with the precision of synchronized fighter jets",
    "fighting tooth and nail for every millimeter of racing asphalt on the track",
    "engaged in a high-speed dogfight that has spectators screaming at the barriers",
    "sparring side-by-side through the carousel, tires screaming in equal agony",
    "testing each other's mental resolve with ruthless defensive block passes",
    "running identical telemetry traces while banging wheels on corner entry",
    "dueling through the chicane with synchronized counter-steers and roaring exhausts",
    "trading the race lead three times in the span of four hundred meters",
    "sparring through the downhill drops with zero margin for mechanical error",
    "locking wheels in a breathless tug-of-war for the championship point",
    "mirroring each other's braking markers with terrifying consistency",
    "throwing dummy moves back and forth in an intense high-stakes tactical chess game",
    "trading paint on the exit curbs with carbon sparks spraying into the night sky",
    "dueling through the blind crest with right feet pinned to the floorboards",
    "running side-by-side into turn one with neither driver touching the brake pedal",
    "battling through the slipstream draft, exchanging lead positions at every timing beam",
    "sparring on the ragged edge of tire grip with millimeter precision",
    "trading slide angles through the S-curves with awe-inspiring car control",
    "dueling for supreme track supremacy with the crowd roaring in absolute delirium",
    "locking horns in a championship-defining scrap that will be remembered forever",
    "pushing each other to the absolute limit of what these racing machines can endure",
    "refusing to concede an inch of tarmac in a duel of raw, unfiltered competitive fire"
  ],
  SLIPSTREAM: [
    "tucked directly into the rival's low-pressure slipstream pocket like a guided homing torpedo",
    "drafted right on the rear bumper diffuser, waiting for the optimal millisecond to slingshot",
    "sucked into the supersonic vacuum wake and pulled alongside with terrifying speed",
    "harnessed the turbulent slipstream draft to gain an effortless thirty kilometers per hour",
    "locked onto the leader's rear wing like a heat-seeking missile tracking its target",
    "utilized the aerodynamic suction zone to slingshot past with unbelievable momentum",
    "tucked into the dead-air envelope, saving fuel and cooling front tires for the attack",
    "swallowed by the low-pressure draft pocket, rocketing forward like a pebble from a sling",
    "drafting so close the front bumper could practically feel the exhaust heat",
    "riding the high-speed tow down the main straight with DRS wide open",
    "sucked along the straightaway on an invisible aerodynamic tether",
    "hitching a free ride in the lead car's vacuum before launching the counterattack",
    "closing a ten-meter gap in the blink of an eye thanks to devastating slipstream suction",
    "tucked under the rear diffuser, letting atmospheric pressure do the heavy lifting",
    "riding the wake of displaced air like a surfboard catching a massive ocean wave",
    "snapped out of the slipstream tow at 320 km/h to challenge for the corner entry",
    "drafting in the low-drag corridor, tachometer climbing straight into the redline",
    "harnessing aerodynamic tow to build up an overwhelming speed delta of 40 km/h",
    "hovering on the rear wing endplates, waiting for the defending car to twitch",
    "sucked into the turbulent air funnel, matching every steering adjustment of the leader",
    "using the aerodynamic tow to slingshot past on the outside before turn three",
    "milking every scrap of reduced air resistance down the long back straight",
    "locked into the high-speed slipstream slipknot, preparing for the decisive dive-bomb",
    "tucked into the draft with surgical discipline, conserving tire rubber for the final lap",
    "blasting through the speed trap courtesy of a massive double slipstream tow",
    "catching the turbulent draft wave and riding it all the way to the lead",
    "harnessing the vacuum tunnel behind two battling cars to overtake both at once",
    "towed along at terrifying velocity before springing out to seize the inside line",
    "locking into the aerodynamic draft pocket like a precision docking maneuver",
    "riding the tailwind of raw horsepower to launch a devastating attack",
    "exploiting the slipstream corridor to set the fastest sector time of the weekend",
    "slingshotting past with such overwhelming draft speed that resistance was futile"
  ],
  COLLISION: [
    "survived a ferocious high-speed wheel contact that sent carbon fiber fragments airborne",
    "bumped quarter-panels hard through the apex but miraculously kept the nose pointed straight",
    "absorbed a massive side impact against the tire barrier and rejoined without lifting throttle",
    "bounced off the concrete safety wall with sparks flying and accelerated straight through",
    "clashed carbon-fiber wheels in a violent impact, shaking off the hit like an iron gladiator",
    "traded heavy body blows through the corner with parts flying, yet neither machine yielded",
    "kissed the steel armco barrier at 250 km/h, showering the chase cars in golden sparks",
    "survived a wild mid-corner bump-and-run that sent shockwaves through the chassis",
    "clipped the concrete apex barrier with the front wheel and powered out on full boost",
    "collided side-by-side with rival, body panels groaning under massive mechanical stress",
    "survived a heavy rear-end tap, catching the resultant slide with legendary composure",
    "scraped down the safety fencing with titanium sparks illuminating the night sky",
    "banged wheels in a bone-jarring impact that visibly bent the front steering tie-rod",
    "absorbed a punishing blow to the sidepod, maintaining racing speed with sheer grit",
    "sideswiped the tire wall on corner exit and kept the hammer down without flinching",
    "shook off a heart-stopping wheel interlock that came within inches of launching both cars",
    "shattered a front wing endplate against the rival's diffuser and continued the charge",
    "ricocheted off the inside curb into the defending car, yet drove away in the lead",
    "withstood a ferocious side-impact shunt that would have totaled a lesser vehicle",
    "traded paint and body panels down the straight, carbon debris raining onto the tarmac",
    "took a direct hit to the rear quarter panel and counter-steered out of disaster",
    "brushed against the retaining wall at Mach speed, stripping the vinyl decals clean off",
    "survived a three-car crunch in the tight chicane, escaping through the tire smoke",
    "absorbed a massive jolt that tore off the left aerodynamic mirror, throttle wide open",
    "glanced off the steel Armco barrier, bouncing back onto the racing line with composure",
    "rubbed tires at 300 km/h, smoke billowing from rubbing sidewalls before pulling ahead",
    "survived a crunching collision that sent the steering wheel jerking in the driver's hands",
    "rammed the outside curb after contact, flying through the air before landing on line",
    "emerged from a high-speed collision with smoking tires and an unyielding desire to win",
    "shook off a savage wheel bang that left black tire marks down the entire side of the chassis",
    "traded violent body checks through the hairpin like two heavyweights in the twelfth round",
    "survived a terrifying brush with disaster, driving through the sparks like a true warrior"
  ],
  FINISH: [
    "crossed the finish line waving to the crowd with fireworks exploding overhead",
    "took the checkered flag with a thunderous victory burnout that blanketed the front straight",
    "clinched the gold trophy with a razor-thin margin of just two thousandths of a second",
    "stormed past the checkered flag in supreme dominance, sealing an iconic championship victory",
    "drifted across the finish line sideways to crown himself the undisputed king of the raceway",
    "blasted past the checkered banner, unleashing a victory scream that echoed through the paddock",
    "swept across the timing line to etch his name into the golden history books of motorsport",
    "claimed the checkered flag by a nose cone in the closest Grand Prix finish of the decade",
    "ignited the rear tires in a smoky victory donut right on the start-finish line",
    "strode across the line in majestic isolation, a commanding masterclass from green to checkered",
    "clinched the ultimate victory with the crowd on the grandstands going wild with adoration",
    "powered past the checkered flag, pumping his fist out the cockpit window in triumph",
    "sealed an unforgettable triumph that will be talked about for generations to come",
    "drifted across the line at 200 km/h, spraying celebratory rubber smoke into the VIP suites",
    "crossed the timing beam with telemetry clocks flashing green in every single sector",
    "took the championship crown in breathtaking fashion, sending his team crew into tears of joy",
    "stormed to victory against all odds, writing the ultimate racing underdog comeback story",
    "flashed past the checkered flag as camera strobes and fireworks illuminated the podium",
    "took the win by a bumper width after an electrifying last-lap drag race to the line",
    "clinched the Grand Prix trophy with surgical precision, unmatched speed, and ice-cold nerves",
    "swept past the checkered flag to complete one of the most dominant drives in racing history",
    "carved through the final corner to claim victory with ten thousand fans waving banners",
    "cemented his legacy among the all-time greats with an emphatic checkered-flag crossing",
    "took the winner's garland with a sensational burnout that left black rings on the asphalt",
    "sealed the victory with a flawless final lap that broke the all-time raceway track record",
    "crossed the line with both hands raised, basking in the glory of hard-fought racing triumph",
    "took the gold medal after an unbelievable battle that had the entire world holding its breath",
    "stormed past the flag as team radio communications erupted into pure, unfiltered ecstasy",
    "clinched the victory crown with a heroic final sector that left rivals trailing in his dust",
    "drifted across the line with championship swagger, confirming his status as the apex king",
    "sealed an epic victory that will be celebrated in racing history for decades to come",
    "took the checkered flag to stand atop the podium as the undisputed champion of the world"
  ],
  LEADER: [
    "extended a commanding three-second gap out front, setting a blistering new lap record",
    "controlled the race pace like a veteran maestro conducting an automotive orchestra",
    "carved clean air ahead with unmatched lap-time consistency down to the hundredth",
    "dictated the entire tempo of the Grand Prix with effortless championship swagger",
    "striding out front in majestic isolation, pulling a gap that breaks the spirit of all pursuers",
    "pulled half a second per sector out front, disappearing into the distant horizon",
    "managing tire wear and fuel mixture with the clinical precision of a chess grandmaster",
    "carving through backmarkers with imperious authority, maintaining a huge lead margin",
    "setting consecutive purple sectors while cruising comfortably on ninety percent throttle",
    "cruising out front with the calm demeanor of a champion out for a Sunday afternoon drive",
    "laying down qualifying-level lap times while controlling the gap from the front of the pack",
    "orchestrating the race from P1, leaving the rest of the field squabbling over crumbs",
    "displaying ungodly pace in clean air, building a fortress-like lead at the head of the grid",
    "holding court at the front of the field with untouchable aerodynamic dominance",
    "lapping the circuit with metronomic consistency, hitting every single apex to the millimeter",
    "controlling the delta to second place like an experienced general commanding his forces",
    "blazing a trail of purple sector times across the live timing monitors",
    "commanding the lead with absolute authority, showing why he wears the number one plate",
    "cruising out front while rivals behind burn up their tires in futile pursuit",
    "setting the standard for excellence with every majestic sweep around the raceway",
    "holding an unassailable lead that turns the battle for first into an exhibition of greatness",
    "dominating every metric of telemetry, from braking efficiency to corner-exit velocity",
    "commanding the front of the field with untouchable grace, pace, and mechanical mastery",
    "dictating the race restart with cunning gamesmanship that caught the pack sleeping",
    "extending the lead with effortless superiority, carving his path through clean air",
    "demonstrating a level of vehicular harmony that leaves competitors shaking their heads",
    "pulling away by another two tenths per lap with absolute clinical perfection",
    "commanding P1 with the untouchable poise of a legendary racing monarch",
    "setting the fastest lap of the race on worn tires just to make a statement to the grid",
    "controlling the entire Grand Prix narrative from the driver's seat with supreme mastery",
    "floating away from the chasing pack like a ghost on an open asphalt highway",
    "holding the lead with the quiet, devastating confidence of a master craftsman"
  ],
  CRASH_SAVE: [
    "executed an impossible opposite-lock steering correction to save the car from a 300 km/h wall crash",
    "gathered up a violent tank-slapper slide through sheer instinct and lightning reflexes",
    "skimmed the grass verge with two wheels and snapped the chassis back onto the racing line",
    "recovered from what looked like an inevitable rollover with supernatural car control",
    "wrestled the violent steering kickback, snatching the car back from the brink of oblivion",
    "caught a terrifying four-wheel snap-spin with lightning-fast countersteer and full throttle",
    "kissed the gravel trap at 260 km/h and feathered the gas to keep the nose pointed forward",
    "counter-steered through a violent tank-slapper that would have destroyed any ordinary vehicle",
    "skated across the wet grass margin and rejoined the track without losing a single position",
    "saved a catastrophic high-speed drift on the wet white line through sheer muscle memory",
    "miraculously avoided a three-car pileup by sliding through an escape gap narrower than a door",
    "wrestled a vicious snap-oversteer twitch while descending the high-speed downhill plunge",
    "gathered up a wild sideways tank-slapper right before the concrete retaining barrier",
    "clawed the car back from a 360-degree spin, stomping the throttle to keep momentum alive",
    "threaded between the spinning lead car and the tire wall with centimeters to spare",
    "snapped the car straight after two wheels were launched over the dangerous sausage curb",
    "recovered from a terrifying suspension bottom-out that threw sparks ten feet into the air",
    "wrestled the wheel like a rodeo rider, keeping the machine on all four tires against all odds",
    "executed an emergency brake-slide that stopped the car two inches from the safety barrier",
    "caught a horrific high-speed snap that made the entire pit garage hold their collective breath",
    "gathered up the violently yawing chassis with cat-like reflexes and surgical poise",
    "snatched victory from the clutches of total destruction with an unbelievable steering save",
    "recovered from a brutal aquaplaning slide on standing water without lifting his right foot",
    "counter-steered out of a violent barrier slap, maintaining forward drive with zero hesitation",
    "clawed back control on the slippery runoff strip and snapped back into the race battle",
    "escaped a certain rollover by burying the throttle and letting aerodynamic downforce bite",
    "survived a heart-stopping two-wheel moment over the curbs, landing flat and powering out",
    "caught a catastrophic slide on cold slick tires that had the corner marshals diving for cover",
    "wrestled the violent chassis oscillations to a standstill through sheer arm strength and grit",
    "pulled off a miraculous crash avoidance that defied every known law of kinetic energy",
    "snatched the steering wheel from the edge of disaster, turning near-death into racing glory",
    "executed the greatest crash save in motorsport history, earning a standing ovation from rivals"
  ]
};

// ============================================================================
// 6. 100 HILARIOUS STAKES & VIRAL WAGERS (MASSIVE_FUNNY_STAKES_EN)
// ============================================================================
export const MASSIVE_FUNNY_STAKES_EN: string[] = [
  "racing desperately to beat his wife's 9:00 PM curfew before the front door gets bolted shut!",
  "trying to settle an unpaid debt for a piping hot bowl of rare beef pho before the shop closes!",
  "fleeing the highway traffic patrol who have sirens blaring in hot pursuit down the service road!",
  "treating five hundred homies to an all-you-can-eat seafood hotpot banquet if he wins today!",
  "running like his mom is charging down the hallway waving a feather broom in fury!",
  "earning enough prize money to redeem a pawned diamond wedding ring before anniversary dinner!",
  "competing to see who gets stuck washing the entire football team's dirty boots for a full calendar year!",
  "fighting over the very last VIP ticket to Taylor Swift's sold-out stadium concert tour!",
  "desperately evading an angry loan shark who showed up trackside demanding immediate hotpot reimbursement!",
  "because the strict head coach threatened to bench anyone who doesn't secure a podium finish today!",
  "racing to deliver a stack of high-tech takeout pizzas before the fifteen-minute guarantee expires!",
  "trying to settle a heated FIFA gaming argument over who really has the superior dribbling statistics!",
  "with the loser being forced to dye their hair glowing neon pink before tomorrow's live press conference!",
  "running from the neighborhood watch captain who is armed with a megaphone and twelve noise complaints!",
  "driven by the promise of free unlimited spicy noodle bowls at the team cafeteria for an entire season!",
  "because his mother called warning that parents are coming home early from vacation in fifteen minutes!",
  "determined to prove that his customized exhaust sound system is superior to any stadium rock concert!",
  "with the defeated driver doomed to perform an embarrassing fan dance in front of 500 sports reporters!",
  "fighting tooth and nail to secure the lone reserved VIP parking slot at the stadium training grounds!",
  "because the team sponsor promised a solid gold trophy filled with bubble tea to the race victor!",
  "desperate to avoid having his embarrassing karaoke singing video leaked to thirty million followers!",
  "trying to dodge a blind date that his aunt set up for seven o'clock this evening!",
  "racing to get to the department store before the ninety-percent-off sneaker sale sells out!",
  "with the loser obligated to wear an inflatable dinosaur suit to the official championship gala!",
  "trying to escape doing the dishes for the next three months straight!",
  "because his best friend bet him ten thousand dollars he couldn't win on three cylinders!",
  "desperately trying to beat the tow truck to his illegally parked car outside the raceway gate!",
  "racing to pick up his little sister from kindergarten before she tells mom everything!",
  "trying to win enough cash to buy an ultra-rare vintage comic book in mint condition!",
  "with the defeated rival doomed to eat a spoonful of pure ghost pepper hot sauce on live stream!",
  "fighting to keep his bragging rights in the family WhatsApp group chat for the next decade!",
  "because the team engineer promised to wash his personal car with baby shampoo if he wins!",
  "racing home to stop his dog from chewing up the expensive leather living room sofa!",
  "trying to prove to his father-in-law that professional racing is a legitimate career path!",
  "with the loser having to shave their eyebrows on a viral TikTok live broadcast!",
  "competing for the ultimate prize: naming rights to the team's new baby mascot bulldog!",
  "racing against the clock to submit an online university essay before the midnight deadline!",
  "desperately trying to avoid having his high school yearbook picture posted on the main billboard!",
  "driven by an insatiable craving for midnight spicy fried chicken with cold boba milk tea!",
  "because his girlfriend promised to say yes to his marriage proposal only if he brought home P1!",
  "racing to prove that manual transmission cars are superior to electric scooters!",
  "with the loser forced to sing the national anthem on a live broadcast while holding a cactus!",
  "trying to win back the family heirloom golden watch that he lost in an arm-wrestling contest!",
  "desperate to escape a twenty-page handwritten lecture from his personal fitness trainer!",
  "racing to claim the last slice of pepperoni pizza left in the team motorhome fridge!",
  "with his entire social media dignity on the line in front of forty million followers!",
  "trying to settle a heated bet over who can make the loudest exhaust backfire in the paddock!",
  "because the team owner promised to buy everyone round-trip tickets to Tokyo if they take P1!",
  "racing to beat the rain before his convertible roof leaks all over the leather interior!",
  "trying to earn enough prize money to pay off three months of overdue electricity bills!",
  "with the loser required to do fifty burpees on the podium while singing nursery rhymes!",
  "fleeing the dentist's office after skipping a scheduled root canal appointment this morning!",
  "racing to retrieve his smartphone from the team bus before his private text messages are read!",
  "driven by pure sibling rivalry that has been brewing since tricycle races in kindergarten!",
  "because the losing driver has to carry all the mechanics' heavy toolboxes for the entire season!",
  "trying to prove that his customized turbo setup was worth spending his life savings on!",
  "racing to catch the last international flight out of town for an exotic beach holiday!",
  "with the defeated driver doomed to wear a rival team cap for thirty days straight!",
  "trying to avoid paying for an expensive weekend golf trip for his four best friends!",
  "because his personal chef promised to cook twelve racks of barbecue ribs if he finished first!",
  "racing to pick up dry cleaning before the shop closes for a three-week summer break!",
  "trying to escape an embarrassing dare where the loser has to dance in the paddock fountain!",
  "with five thousand dollars worth of fresh durian fruit on the line in a bet with his uncle!",
  "racing to stop his younger brother from selling his prized gaming console on eBay!",
  "because the team doctor threatened to put him on a strict boiled broccoli diet if he lost!",
  "trying to prove that he doesn't need GPS navigation to find the fastest way around a circuit!",
  "with the loser having to walk the entire perimeter of the track barefoot at midnight!",
  "racing to get home before his ice cream cake melts in the trunk under the midday sun!",
  "trying to win enough prize money to buy his grandmother a brand-new electric massage chair!",
  "because his best friend threatened to post his baby photos on every billboard in the city!",
  "racing to prove to his childhood bullies that he really did become a world-class race champion!",
  "with the defeated driver forced to act as the winner's personal butler for forty-eight hours!",
  "trying to settle a bet over who has the fastest reaction time outside of an espresso bar!",
  "because the local bakery promised free fresh croissants for life to the hometown race winner!",
  "racing home to water his wife's rare orchid plants before they wither and trigger divorce papers!",
  "trying to avoid paying for eighty rounds of iced coffee at the city center cafe!",
  "with his favorite racing jacket on the line against the defending championship veteran!",
  "racing to escape a lecture from his high school math teacher who is watching from the VIP suite!",
  "because his fitness coach bet him fifty protein shakes that he couldn't break the lap record!",
  "trying to prove that his lucky neon racing socks actually possess magical victory powers!",
  "with the loser forced to eat a whole raw onion without blinking on a live streaming broadcast!",
  "racing to deliver a package of fresh hot dumplings to his grandfather before they get soggy!",
  "trying to earn enough prize cash to fund his cousin's indie garage rock album release!",
  "because the rival team principal laughed at his custom aerodynamic wing at the morning briefing!",
  "racing to catch the season finale of his favorite anime series before internet spoilers ruin it!",
  "trying to escape a mandatory three-hour team corporate accounting seminar on Monday morning!",
  "with the defeated driver doomed to wear swimming goggles and flippers around the paddock!",
  "racing to prove that pure instinct trumps two hundred computer simulations every single day!",
  "trying to win a golden trophy large enough to use as a luxury punch bowl for tonight's party!",
  "because his mother told the entire neighborhood that her son was going to win the gold today!",
  "racing to save enough money to buy his dream vintage garage workshop in the countryside!",
  "with a hundred boxes of gourmet Belgian chocolate on the line between the two rival crews!",
  "trying to dodge his landlord who is currently standing at the paddock entrance waving overdue rent receipts!",
  "because the loser has to clean every speck of tire rubber off the winning car by hand!",
  "racing to win the wager and finally get his friend to admit that Ronaldo is the true GOAT!",
  "trying to prove that his dog has better tactical instincts than the competitor's race engineer!",
  "with the defeated driver forced to dress up as a giant hotdog mascot at the next fan fest!",
  "racing with everything on the line just to see the stunned look on the second-place driver's face!",
  "because winning this race is the only way he gets out of washing the team motorhome toilet!",
  "and to prove once and for all who truly rules this asphalt jungle with an iron foot!"
];

// ============================================================================
// 7. 60 AUDIENCE & OFFICIAL REACTIONS (AUDIENCE_REACTIONS_EN)
// ============================================================================
export const AUDIENCE_REACTIONS_EN: string[] = [
  "The lead referee's eyes go wide in shock as his golden whistle drops right out of his mouth!",
  "The lead commentator slams the broadcast desk so hard he nearly snaps the microphone in half!",
  "The entire grandstand erupts in unison, hurling hats and jackets into the air in wild celebration!",
  "The trailing rival in second place is furiously biting his fingernails in bitter regret!",
  "Pit crew mechanics are spraying mineral water and champagne all over the timing pit wall!",
  "Two million live-stream viewers are spamming red flames and skull emojis at light speed!",
  "The track marshals are rubbing their eyes wondering if that maneuver violated federal aviation laws!",
  "Pundits in the broadcast studio are jumping on their desks pointing at the replay monitors!",
  "The team principal just smashed his headset against the pit wall in sheer disbelief!",
  "A collective gasp of shock echoed across sixty thousand spectators in the grandstands!",
  "The crowd is chanting his name so loud it's drowning out the roar of the V12 engines!",
  "Social media servers are practically crashing under the avalanche of viral highlight clips!",
  "Every spectator on the main straight is holding their smartphone camera up in awe!",
  "The rival team pit wall has gone deathly silent as their strategy completely unravels!",
  "Security guards are struggling to hold back the tsunami of ecstatic fans at the podium fence!",
  "The co-commentator is hyperventilating into the mic, completely lost for technical words!",
  "VIP celebrities in the hospitality paddock are standing on champagne tables cheering!",
  "Race stewards are staring at the telemetry screens with jaws resting on the floorboards!",
  "The trackside photographers are firing motor-drives at twelve frames a second in sheer ecstasy!",
  "Young fans in the bleachers are waving homemade banners and lighting up yellow flares!",
  "The defending champion in the garage is shaking his head in reluctant, awe-struck respect!",
  "The pit garage engineers are hugging each other with tears streaming down their faces!",
  "A sonic boom of cheer erupts from the main grandstand, shaking the television cameras!",
  "The track announcer's voice breaks into an emotional scream of pure unfiltered joy!",
  "The timing screens are flashing all-purple as the entire paddock gasps in unison!",
  "Rival mechanics are dropping their impact wrenches in utter, helpless disbelief!",
  "Grandstand fans are doing the Mexican wave at triple speed across the entire stadium bowl!",
  "The race director is leaning forward with binoculars glued to his face, entirely captivated!",
  "Spectators are slapping each other on the back, unable to believe what they just witnessed!",
  "Live-stream chat is moving so fast the text is blurring into an unreadable river of hype!",
  "Veteran journalists in the press box are tearing up their draft articles to rewrite history!",
  "The team radio channel is a chaotic cacophony of celebratory screams and euphoric sobs!",
  "Corner marshals are enthusiastically waving green flags and giving emphatic thumbs-up!",
  "Fans in the front row are clinging to the safety fence with tears of adrenaline in their eyes!",
  "The opposing team's chief strategist is frantically calculating where it all went wrong!",
  "The stadium decibel meter just spiked past the threshold of a commercial jet taking off!",
  "Children in the crowd are jumping up and down mimicking the driver's steering motions!",
  "The television broadcast director is frantically switching angles to keep up with the chaos!",
  "Sponsors in the executive lounge are clinking crystal glasses and cheering like wild wolves!",
  "The race engineer is shouting down the radio headset: 'You absolute beauty, that was legend!'",
  "The opposing driver is gesturing in disbelief from inside his cockpit, totally defeated!",
  "Spectators are throwing confetti and team scarves over the catch-fencing into the pit lane!",
  "The pit wall telemetry computers are glowing green as every sector record falls at once!",
  "Fans across thirty countries are uploading viral clips that are already trending number one!",
  "The medical car driver is nodding in sheer appreciation of that otherworldly car control!",
  "The team hospitality chef is already firing up the victory barbecue and popping vintage bottles!",
  "The crowd is drumming on the metal advertising boards, creating a deafening thunderclap!",
  "The second-place driver's face looks like he just witnessed a supernatural phenomenon!",
  "Every cameraman on the circuit is smiling, knowing they just captured pure gold!",
  "The track temperature sensors are spiking from the intense heat of screaming rubber and applause!",
  "Supporters are waving giant flags that ripple across the entire length of turn three!",
  "The television producer is screaming in the audio feed: 'Keep rolling, this is television history!'",
  "The opposing team's sponsor looks like he wants to offer the winner a blank check on the spot!",
  "The race marshals on post seven are giving each other high-fives across the tyre wall!",
  "The crowd's roar echoes across the mountain valley like rolling summer thunder!",
  "A sea of smartphone flashlights turns the grandstands into a magical galaxy of light!",
  "The chief mechanic is running down the pit lane waving a pit board that says 'P1 LEGEND'!",
  "Broadcasters across five continents are simultaneously losing their composure on air!",
  "The driver's mother in the hospitality box is crying tears of overwhelming pride and joy!",
  "And the entire racing world unites in stunned, breathless applause for a master at work!"
];

// ============================================================================
// 8. 100 VIRAL OUTROS & PUNCHLINES (MASSIVE_OUTROS_EN)
// ============================================================================
export const MASSIVE_OUTROS_EN: string[] = [
  "Pure poetry in motion!",
  "That is why they call him the undisputed apex predator of the asphalt!",
  "Good grief, what an unbelievable spectacle of mechanical fury!",
  "Drop the mic, nobody on planet Earth is topping that lap today!",
  "A masterclass that will be talked about for decades in racing folklore!",
  "Unbelievable scenes, simply out of this world!",
  "That is how legends are carved into the annals of racing history!",
  "Take a bow, champion, you have earned every ounce of this glory!",
  "Fasten your seatbelts for the post-race fireworks, because this is far from over!",
  "What an astonishing display of sheer grit, determination, and horsepower!",
  "Put some respect on his name, because that was racing divinity in motion!",
  "Absolute cinematic perfection delivered at triple-digit speeds!",
  "Frame this moment and hang it in the Louvre museum of motorsport!",
  "They came, they saw, and they conquered the asphalt like true gods of speed!",
  "That wasn't just a race maneuver; that was an artistic statement of dominance!",
  "Simply majestic, simply ruthless, simply sensational in every single way!",
  "He didn't just take the lead; he stole their souls right through the apex!",
  "Ladies and gentlemen, we have just witnessed automotive immortality!",
  "Give this driver a medal, a trophy, and the keys to the entire city right now!",
  "A high-octane symphony conducted by an absolute racing virtuoso!",
  "Write it down, remember the date, because history was rewritten right here!",
  "No scriptwriter in Hollywood could have dreamed up a finish this dramatic!",
  "From this day forth, they will speak of this lap in hushed, reverent whispers!",
  "He came with a point to prove, and he hammered it home with titanium force!",
  "That is what happens when God-given talent meets unyielding horsepower!",
  "Stand up and applaud, sports fans, because greatness just walked the stage!",
  "An absolute clinic in vehicle dynamics, bravery, and tactical cunning!",
  "The speedometer has melted, the record books are burning, and the crowd is in ecstasy!",
  "There are drivers, there are champions, and then there is this immortal legend!",
  "Blink once, and you missed the greatest overtaking masterclass of the century!",
  "He drove that machine like he stole it from the gates of destiny itself!",
  "That maneuver was so clean you could eat dinner off the racing line!",
  "Nothing short of an earthquake on wheels that shook the foundation of the sport!",
  "Crown him king of the raceway and bow down to the asphalt sovereign!",
  "Heart of a lion, hands of a surgeon, and the speed of a thunderbolt!",
  "That was not just driving; that was a spiritual awakening on four forged rims!",
  "He didn't leave breadcrumbs for the competition; he devoured the whole bakery!",
  "The checkered flag never looked so sweet, and victory never tasted so rich!",
  "A victory forged in the fire of competition and tempered in icy determination!",
  "Pack up the trailers, folks, because the competition has been thoroughly dismantled!",
  "Pure unadulterated swagger backed up by blistering, law-defying lap times!",
  "They tried to contain him, but you cannot put a cage around a hurricane!",
  "That was textbook perfection delivered with a cheeky wink to the cameras!",
  "An iconic drive that will be replayed twenty million times before the sun sets!",
  "He took the rulebook, tore it to shreds, and wrote his own chapter of speed!",
  "Motorsport at its absolute zenith, its purest essence, its finest hour!",
  "A jaw-dropping performance that left the entire racing world speechless!",
  "He danced on the edge of the abyss and came out smelling of high-octane roses!",
  "Give that man a standing ovation, because he just gave us the ride of our lives!",
  "A ruthless display of competitive excellence that will stand the test of time!",
  "That was an intergalactic performance delivered on planet Earth!",
  "He turned turn one into his personal playground and the rivals into spectators!",
  "The legend grows, the myth expands, and the trophy heads straight to his mantle!",
  "If you don't love motorsport after watching that, check your pulse immediately!",
  "Sensational, magnificent, extraordinary, and utterly unstoppable!",
  "He didn't just win the race; he made a definitive statement to the entire universe!",
  "A masterclass in momentum, aggression, and calculated precision!",
  "That is how a champion responds under maximum atmospheric pressure!",
  "Hang it in the gallery of greatness, because that was pure racing art!",
  "He came, he saw, he hit the apex, and he conquered all before him!",
  "An adrenaline rush that will keep our hearts pounding until next Sunday!",
  "He didn't just break the track record; he obliterated it into cosmic dust!",
  "That was pure titanium grit wrapped in high-downforce carbon fiber!",
  "A breathtaking finale that will be etched into racing folklore forever!",
  "He proved beyond any shadow of a doubt who the true king of the circuit is!",
  "A performance of such sheer magnitude that words simply fail to do it justice!",
  "Raise your glass to the winner, because today he was utterly untouchable!",
  "A symphonic triumph of machine and human instinct working as one single entity!",
  "He drove that lap with the fire of a warrior and the finesse of an artist!",
  "The greatest show on four wheels delivered the greatest climax in racing history!",
  "Shut down the timing beams, because nobody is ever going faster through that turn!",
  "He looked danger straight in the eyes, smiled, and stepped harder on the throttle!",
  "An absolute tour de force that redefined what is possible on racing rubber!",
  "The roar of the crowd says everything: a generational talent taking center stage!",
  "He didn't just cross the finish line; he flew across it into the history books!",
  "That was sports entertainment at its absolute absolute pinnacle!",
  "Unrivaled speed, unmatched courage, and an unforgettable championship performance!",
  "He carved his name into racing eternity with every turn of the steering wheel!",
  "Take notes, young drivers, because you just witnessed the gold standard of racing!",
  "A dramatic triumph that will echo through the racing paddocks for decades!",
  "He conquered the asphalt, tamed the elements, and vanquished the entire field!",
  "A victory that will be celebrated from the streets of the city to the ends of the Earth!",
  "The pinnacle of motorsport excellence demonstrated with effortless swagger!",
  "He didn't just participate; he dominated from the first green light to the checkered flag!",
  "A thrilling masterclass that had two million viewers screaming at their screens!",
  "Pure genius, pure speed, pure unadulterated racing ecstasy!",
  "That is how you leave your rivals in the rearview mirror of history!",
  "He stood on the throttle, held his nerve, and seized his rightful crown!",
  "An unforgettable display of mechanical fury and human determination!",
  "He didn't just win today; he etched his legend into the bedrock of racing glory!",
  "The ultimate reward for the ultimate driver on the ultimate racing stage!",
  "A triumph of courage, engineering, and sheer unyielding will to succeed!",
  "He turned high-speed chaos into an elegant dance of pure sporting perfection!",
  "That was the performance of a lifetime, and we were privileged to witness it!",
  "Bow down to the champion, because today he drove among the gods of speed!",
  "A breathtaking spectacle that reminded the entire world why we love this sport!",
  "He stamped his authority on this championship with an exclamation point!",
  "Unstoppable, unbelievable, undeniable, and utterly unforgettable!",
  "The gold trophy has found its rightful owner, and the celebrations have only just begun!",
  "And that, ladies and gentlemen, is how you become a racing legend forever!"
];
