// 100 KHÚC CUA VÀ ĐOẠN CHUYỂN HƯỚNG ĐẦY KỊCH TÍNH TRÊN ĐƯỜNG ĐUA (100 TRACK TWISTS)
export const TRACK_TWISTS_VI: string[] = [
  "Đột nhiên những đợt xả khí nitro đột ngột từ van an toàn khiến chiếc xe bốc đầu bay là là trên không trung!",
  "Một chú mèo hoang xuất hiện bất ngờ trên đỉnh dốc cua khiến tay đua phải biểu diễn cú drift 360 độ né tránh!",
  "Cơn bão nhiệt đới gió giật dữ dội quét qua đường đua làm bay sạch khói lốp, để lộ khoảng cách chỉ 0.01 giây!",
  "Khói mù mịt từ hệ thống âm thanh điện ảnh subwoofer phát nổ bao trùm toàn bộ tầm nhìn của các tay đua!",
  "Tiếng loa phóng thanh của ban huấn luyện gào thét vang dội khiến cả hai tay đua giật mình đè lún chân ga!",
  "Mặt đường trơn trượt như đổ xà phòng, những cỗ máy 700 mã lực bắt đầu lướt sóng nghệ thuật trên nhựa đường!",
  "Cánh gió sau bung khóa khí động học, tạo luồng gió xoáy hút đối thủ vào thế bám đuôi nghẹt thở!",
  "Tiếng còi cảnh sát hú vang phía sau khiến các tay đua tưởng bị bắt thật, đồng loạt vặn ga tẩu thoát!",
  "Lốp xe bắt đầu bốc khói cam rực rỡ, ma sát nóng chảy cả nhựa đường bên dưới theo từng cú vẩy đuôi!",
  "Chiếc xe phía sau kích hoạt chế độ siêu tăng áp bí mật, vút lên như tên lửa hành trình xuyên thủng bóng đêm!",
  "Biến cố #11: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #12: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #13: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #14: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #15: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #16: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #17: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #18: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #19: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #20: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #21: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #22: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #23: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #24: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #25: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #26: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #27: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #28: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #29: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #30: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #31: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #32: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #33: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #34: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #35: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #36: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #37: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #38: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #39: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #40: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #41: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #42: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #43: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #44: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #45: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #46: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #47: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #48: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #49: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #50: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #51: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #52: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #53: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #54: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #55: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #56: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #57: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #58: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #59: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #60: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #61: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #62: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #63: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #64: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #65: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #66: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #67: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #68: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #69: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #70: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #71: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #72: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #73: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #74: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #75: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #76: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #77: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #78: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #79: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #80: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #81: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #82: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #83: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #84: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #85: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #86: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #87: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #88: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #89: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #90: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #91: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #92: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #93: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #94: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #95: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #96: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #97: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #98: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #99: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!",
  "Biến cố #100: Một luồng gió xoáy cực mạnh tại khúc cua chữ S đẩy chiếc xe trượt nghiêng hai bánh trên dải rào chắn an toàn!"
];

export const TRACK_TWISTS_EN: string[] = [
  "Sudden nitro purge valve discharges caused the front wheels to lift into a prolonged ground-effect flight!",
  "A fearless stray cat perched right on the crest of the hairpin apex, forcing an astonishing 360-degree evasive drift!",
  "A violent tropical storm sweeping across the tarmac blew away tire smoke to reveal a microscopic 0.01-second bumper gap!",
  "Dense cinematic smoke billowing from exploded audio subwoofers completely blinded all oncoming cockpits!",
  "Furious radio orders from team management echoed across the PA system, compelling both drivers to bury the throttle!",
  "The tarmac turned slick as soap, prompting 700-horsepower machines into an acrobatic synchronized drift ballet!",
  "The rear wing unlocked into hyper-slipstream mode, creating a vacuum vortex pulling the rival into intense drafting!",
  "Screaming emergency sirens in the distance prompted drivers to treat the track as an outlaw escape corridor!",
  "Tires began spewing brilliant neon orange smoke, liquifying surface asphalt under staggering friction forces!",
  "The trailing machine engaged an illicit overboost map, rocketing forward like a laser-guided cruise missile!",
  "Twist #11: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #12: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #13: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #14: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #15: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #16: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #17: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #18: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #19: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #20: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #21: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #22: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #23: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #24: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #25: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #26: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #27: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #28: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #29: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #30: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #31: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #32: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #33: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #34: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #35: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #36: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #37: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #38: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #39: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #40: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #41: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #42: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #43: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #44: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #45: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #46: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #47: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #48: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #49: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #50: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #51: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #52: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #53: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #54: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #55: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #56: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #57: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #58: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #59: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #60: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #61: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #62: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #63: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #64: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #65: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #66: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #67: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #68: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #69: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #70: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #71: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #72: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #73: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #74: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #75: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #76: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #77: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #78: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #79: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #80: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #81: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #82: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #83: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #84: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #85: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #86: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #87: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #88: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #89: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #90: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #91: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #92: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #93: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #94: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #95: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #96: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #97: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #98: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #99: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!",
  "Twist #100: A severe vortex draft at the S-curve sent the machine tilting onto two wheels along the safety barrier!"
];

// 100 HÌNH PHẠT HÀI HƯỚC (100 PUNISHMENTS / CONSEQUENCES)
export const CONSEQUENCES_VI: string[] = [
  "phải nhuộm tóc màu hồng neon rực rỡ và giữ nguyên kiểu tóc suốt cả mùa giải",
  "phải mặc váy tutu ba-lê bồng bềnh tham dự buổi họp báo quốc tế trước 500 phóng viên",
  "phải biểu diễn múa quạt trực tiếp trên sóng livestream 8 tiếng liên tục trước 1 triệu người xem",
  "phải giặt và đánh bóng giày thi đấu cho toàn bộ thành viên trong đội suốt một năm ròng rã",
  "phải mặc váy dạ hội xẻ tà phục vụ trà đá vỉa hè cho cả xóm suốt mùa hè",
  "bị tịch thu toàn bộ điện thoại thông minh và phải dùng máy bàn quay số cổ điển trong 6 tháng",
  "phải đăng video tự thú xin lỗi đối thủ lên mạng xã hội với hashtag #ToiLaKeThuaCuoc",
  "phải khao cả đội 1 chuyến du thuyền sang chảnh và đứng nướng thịt ngoài trời suốt 3 ngày",
  "bị cạo nửa bên đầu và nhuộm màu xanh chuối đi dự lễ trao giải Quả Bóng Vàng",
  "phải đi xe đạp cút kít ba bánh của trẻ con đi tập luyện mỗi ngày suốt một tháng",
  "mức phạt #11: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 11 ngày",
  "mức phạt #12: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 12 ngày",
  "mức phạt #13: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 13 ngày",
  "mức phạt #14: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 14 ngày",
  "mức phạt #15: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 15 ngày",
  "mức phạt #16: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 16 ngày",
  "mức phạt #17: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 17 ngày",
  "mức phạt #18: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 18 ngày",
  "mức phạt #19: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 19 ngày",
  "mức phạt #20: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 20 ngày",
  "mức phạt #21: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 21 ngày",
  "mức phạt #22: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 22 ngày",
  "mức phạt #23: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 23 ngày",
  "mức phạt #24: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 24 ngày",
  "mức phạt #25: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 25 ngày",
  "mức phạt #26: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 26 ngày",
  "mức phạt #27: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 27 ngày",
  "mức phạt #28: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 28 ngày",
  "mức phạt #29: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 29 ngày",
  "mức phạt #30: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 30 ngày",
  "mức phạt #31: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 31 ngày",
  "mức phạt #32: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 32 ngày",
  "mức phạt #33: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 33 ngày",
  "mức phạt #34: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 34 ngày",
  "mức phạt #35: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 35 ngày",
  "mức phạt #36: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 36 ngày",
  "mức phạt #37: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 37 ngày",
  "mức phạt #38: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 38 ngày",
  "mức phạt #39: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 39 ngày",
  "mức phạt #40: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 40 ngày",
  "mức phạt #41: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 41 ngày",
  "mức phạt #42: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 42 ngày",
  "mức phạt #43: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 43 ngày",
  "mức phạt #44: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 44 ngày",
  "mức phạt #45: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 45 ngày",
  "mức phạt #46: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 46 ngày",
  "mức phạt #47: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 47 ngày",
  "mức phạt #48: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 48 ngày",
  "mức phạt #49: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 49 ngày",
  "mức phạt #50: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 50 ngày",
  "mức phạt #51: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 51 ngày",
  "mức phạt #52: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 52 ngày",
  "mức phạt #53: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 53 ngày",
  "mức phạt #54: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 54 ngày",
  "mức phạt #55: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 55 ngày",
  "mức phạt #56: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 56 ngày",
  "mức phạt #57: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 57 ngày",
  "mức phạt #58: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 58 ngày",
  "mức phạt #59: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 59 ngày",
  "mức phạt #60: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 60 ngày",
  "mức phạt #61: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 61 ngày",
  "mức phạt #62: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 62 ngày",
  "mức phạt #63: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 63 ngày",
  "mức phạt #64: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 64 ngày",
  "mức phạt #65: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 65 ngày",
  "mức phạt #66: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 66 ngày",
  "mức phạt #67: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 67 ngày",
  "mức phạt #68: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 68 ngày",
  "mức phạt #69: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 69 ngày",
  "mức phạt #70: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 70 ngày",
  "mức phạt #71: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 71 ngày",
  "mức phạt #72: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 72 ngày",
  "mức phạt #73: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 73 ngày",
  "mức phạt #74: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 74 ngày",
  "mức phạt #75: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 75 ngày",
  "mức phạt #76: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 76 ngày",
  "mức phạt #77: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 77 ngày",
  "mức phạt #78: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 78 ngày",
  "mức phạt #79: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 79 ngày",
  "mức phạt #80: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 80 ngày",
  "mức phạt #81: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 81 ngày",
  "mức phạt #82: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 82 ngày",
  "mức phạt #83: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 83 ngày",
  "mức phạt #84: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 84 ngày",
  "mức phạt #85: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 85 ngày",
  "mức phạt #86: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 86 ngày",
  "mức phạt #87: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 87 ngày",
  "mức phạt #88: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 88 ngày",
  "mức phạt #89: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 89 ngày",
  "mức phạt #90: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 90 ngày",
  "mức phạt #91: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 91 ngày",
  "mức phạt #92: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 92 ngày",
  "mức phạt #93: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 93 ngày",
  "mức phạt #94: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 94 ngày",
  "mức phạt #95: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 95 ngày",
  "mức phạt #96: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 96 ngày",
  "mức phạt #97: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 97 ngày",
  "mức phạt #98: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 98 ngày",
  "mức phạt #99: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 99 ngày",
  "mức phạt #100: phải làm nhân viên dọn dẹp căn-tin và rửa nồi niêu xoong chảo không công suốt 100 ngày"
];

export const CONSEQUENCES_EN: string[] = [
  "must dye their hair fluorescent neon pink and keep the hairstyle for the entire racing season",
  "must wear a frilly ballerina tutu dress at the official international press conference before 500 journalists",
  "must perform a viral fan dance on a live stream for 8 continuous hours before 1 million viewers",
  "must wash and hand-polish boots and shoes for the entire team for one whole year",
  "must wear a sparkling slit evening gown while serving iced sidewalk tea to the entire neighborhood all summer",
  "will have all smartphones confiscated and be restricted to a rotary dial landline phone for six months",
  "must publish an apology confession video on social media with the hashtag #IAmTheDefeatedOne",
  "has to charter a luxury team yacht cruise and act as the sole barbecue chef for three straight days",
  "will have half their head shaved and dyed lime green for the upcoming Ballon d’Or gala",
  "must commute to daily training riding a toddler’s three-wheeled tricycle for an entire month",
  "penalty #11: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 11 days",
  "penalty #12: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 12 days",
  "penalty #13: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 13 days",
  "penalty #14: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 14 days",
  "penalty #15: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 15 days",
  "penalty #16: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 16 days",
  "penalty #17: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 17 days",
  "penalty #18: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 18 days",
  "penalty #19: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 19 days",
  "penalty #20: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 20 days",
  "penalty #21: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 21 days",
  "penalty #22: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 22 days",
  "penalty #23: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 23 days",
  "penalty #24: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 24 days",
  "penalty #25: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 25 days",
  "penalty #26: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 26 days",
  "penalty #27: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 27 days",
  "penalty #28: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 28 days",
  "penalty #29: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 29 days",
  "penalty #30: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 30 days",
  "penalty #31: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 31 days",
  "penalty #32: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 32 days",
  "penalty #33: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 33 days",
  "penalty #34: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 34 days",
  "penalty #35: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 35 days",
  "penalty #36: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 36 days",
  "penalty #37: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 37 days",
  "penalty #38: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 38 days",
  "penalty #39: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 39 days",
  "penalty #40: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 40 days",
  "penalty #41: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 41 days",
  "penalty #42: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 42 days",
  "penalty #43: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 43 days",
  "penalty #44: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 44 days",
  "penalty #45: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 45 days",
  "penalty #46: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 46 days",
  "penalty #47: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 47 days",
  "penalty #48: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 48 days",
  "penalty #49: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 49 days",
  "penalty #50: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 50 days",
  "penalty #51: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 51 days",
  "penalty #52: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 52 days",
  "penalty #53: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 53 days",
  "penalty #54: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 54 days",
  "penalty #55: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 55 days",
  "penalty #56: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 56 days",
  "penalty #57: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 57 days",
  "penalty #58: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 58 days",
  "penalty #59: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 59 days",
  "penalty #60: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 60 days",
  "penalty #61: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 61 days",
  "penalty #62: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 62 days",
  "penalty #63: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 63 days",
  "penalty #64: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 64 days",
  "penalty #65: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 65 days",
  "penalty #66: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 66 days",
  "penalty #67: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 67 days",
  "penalty #68: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 68 days",
  "penalty #69: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 69 days",
  "penalty #70: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 70 days",
  "penalty #71: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 71 days",
  "penalty #72: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 72 days",
  "penalty #73: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 73 days",
  "penalty #74: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 74 days",
  "penalty #75: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 75 days",
  "penalty #76: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 76 days",
  "penalty #77: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 77 days",
  "penalty #78: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 78 days",
  "penalty #79: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 79 days",
  "penalty #80: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 80 days",
  "penalty #81: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 81 days",
  "penalty #82: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 82 days",
  "penalty #83: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 83 days",
  "penalty #84: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 84 days",
  "penalty #85: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 85 days",
  "penalty #86: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 86 days",
  "penalty #87: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 87 days",
  "penalty #88: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 88 days",
  "penalty #89: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 89 days",
  "penalty #90: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 90 days",
  "penalty #91: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 91 days",
  "penalty #92: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 92 days",
  "penalty #93: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 93 days",
  "penalty #94: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 94 days",
  "penalty #95: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 95 days",
  "penalty #96: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 96 days",
  "penalty #97: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 97 days",
  "penalty #98: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 98 days",
  "penalty #99: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 99 days",
  "penalty #100: must serve as unpaid cafeteria dishwasher scrubbing giant cooking pots for 100 days"
];
